### ISSUE TITLE
[Questions] Long term

### ISSUE THREAD

**Issue by jogelin** [JackHack96/dell-xps-9570-ubuntu-respin#1]
Hi there,

I am a developer and I would like to setup a dual boot windows/ubuntu on my dell xps 9570.

So I am looking for the best way to install ubuntu and already read a lot of issues about this exercice. I was mainly going into this solution https://github.com/rcasero/doc/wiki/Ubuntu-linux-on-Dell-XPS-15-(9560) but then I found your fork about ubuntu respin.

I understood that you modify the ubuntu iso file to inject some tweaks but when my installation is done...how could I manage the new tweak/scripts that you will add to this repo ?

I don't really want to install again ubuntu each time you improved something.... ;)

thx for this repo ;)

**Comment by JackHack96** [comment]
I also thought about this possible issue, so I decided to document each tweak I make with the ISO, and with each tweak a way for applying it manually on an already installed system.
I could also write a more general script for applying them automatically :+1: 

The only thing is that for now I'm occupied by university, I'm in full exam session :cry: 
I'll finish in late July though :smile:

**Comment by jogelin** [comment]
Ok cool ! I am gone wait a bit then ;)

Good luck for your exams ;)

**Comment by JackHack96** [comment]
I've made a little wiki for documenting the tweaks, and I wrote a script for applying them post-install (it should work, but I can't fully test it right now).
The script is xps-tweaks.sh
