### ISSUE TITLE
X/Gnome Crashes After 2 Minutes on External Monitor

### ISSUE THREAD

**Issue by craigmediaservices** [JackHack96/dell-xps-9570-ubuntu-respin#101]
I'm running through an external monitor connected via a Dell dock (TB16) on the thunderbolt connection.

Everything works fine on boot, than after about 2 minutes X/Gnome appears crash, screen goes black, peripherals freeze, and about half the time it will all come back after refreshing. Half the time the entire machine freezes and needs to reboot.

Any idea what might be causing the issue or a potential fix? Thank you!

**Comment by lars-berger** [comment]
Also using a TB16 and running into a similar issue. What'd you do to fix it?

**Comment by FlakM** [comment]
What version of bios are you both on?

czw., 27 cze 2019, 19:26 użytkownik lars-berger <notifications@github.com>
napisał:

**Comment by JackHack96** [comment]
I'm sorry but I don't own a dock and I can't test it.
I tested successfully a third-party dock without crashes though.

**Comment by craigmediaservices** [comment]
I'm on the latest bios (Ubuntu update). I'm returning the Dell dock.
