### ISSUE TITLE
xps-tweaks.sh script stuck

### ISSUE THREAD

**Issue by riccardosamperna** [JackHack96/dell-xps-9570-ubuntu-respin#103]
First of all, thanks a lot for all your work. I am trying to run the script xps-tweaks.sh but it gets stuck at "Do you wish to install video codecs for encoding and playing videos?". I have tried to enter "Yes", "yes", "No" and other combination but it looks like the script is not responding to any input. Do you know how to fix it?

**Comment by magrith** [comment]
Enter 1 for yes or 2 for No

**Comment by riccardosamperna** [comment]
Thanks @magrith
