### ISSUE TITLE
Fingerprint occasionally active after disabling it

### ISSUE THREAD

**Issue by enovella** [JackHack96/dell-xps-9570-ubuntu-respin#104]
Hey,

I've observed that even after disabling the Goodix fingerprint as shown below:
```
[02:41 edu@xps ~] >  cat /etc/udev/rules.d/fingerprint.rules
# Disable fingerprint reader
SUBSYSTEM=="usb", ATTRS{idVendor}=="27c6", ATTRS{idProduct}=="5395", ATTR{authorized}="0"
```

The fingerprint was consuming battery as shown by `powertop`:
`            100.0%        USB device: Goodix Fingerprint Device  (HTMicroelectronics)`

Any workaround?

My battery lasts only 4h with Intel graphical card use. My xps15 9570 is i9, 32gb ram and 2TB SSD. Any ideas on where to gain some battery time?

Best

**Comment by aidanthewiz** [comment]
That's weird, mine shows 0%. Can you post the result of 'sudo lsusb' please?

**Comment by enovella** [comment]
Matching device ID:
```
 >  cat /etc/udev/rules.d/fingerprint.rules
# Disable fingerprint reader
SUBSYSTEM=="usb", ATTRS{idVendor}=="27c6", ATTRS{idProduct}=="5395", ATTR{authorized}="0"
```

```
>  lsusb 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 27c6:5395  
Bus 001 Device 003: ID 0cf3:e300 Atheros Communications, Inc. 
Bus 001 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 005: ID 0bda:5657 Realtek Semiconductor Corp. 
Bus 001 Device 006: ID 2717:ff08  
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by aidanthewiz** [comment]
Very weird, I'm assuming you rebooted right? It requires a reboot after the first run. If you did, then I will look into another method of disabling it.

**Comment by enovella** [comment]
Yeah, I set it up yesterday night. After this, it was showing 0% but today it came back to consume battery again.

**Comment by enovella** [comment]
Reboot my system and it works fine:
`              0.0%        USB device: Goodix Fingerprint Device  (HTMicroelectronics)`

But somehow, it can be re-enabled and consume watts. Weird!

**Comment by aidanthewiz** [comment]
Interesting... i'll look into why it might be doing that.

**Comment by enovella** [comment]
After days of suspensions, the Goodix sensor is alive again. :(

**Comment by 0xFireball** [comment]
My system is having the same issue as described above, with the same device as well

**Comment by enovella** [comment]
hey @0xFireball,

can you run `sudo powertop --auto-tune` and check afterwards?

My current issue is this cancer  related to Atheros radio:
`  8.74 W    100.0%                      Device         USB device: usb-device-0cf3-e300`
