### ISSUE TITLE
Killer wifi card messed up from respin

### ISSUE THREAD

**Issue by roushrsh** [JackHack96/dell-xps-9570-ubuntu-respin#106]
Hi,

I had initially got some cuda/nvidia problems when at 19.04 which basically killed grub/ any display driver. 

So I clean installed as 18.04.2, ran the respin curl, and everything was working great. A day later I noticed my wifi was dropping. I would have to restart to fix the issue. I changed network-manager, changed the killer drivers, so on and so forth, for days. I then found a lot of threads of people with similar issues, and they ultimately ended up having to change their killer card for an Intel 9260 to solve this problem. I thought maybe it's a kernel issue and went up to 19.04, and although the frequency of disconnections decreased, it still occurred at least every 10 minutes.

I re-installed again, everything seemed to be working, I ran the respin and installed everything again, and right after wifi was dropping again requiring me to restart network manager.

This time, I clean installed, exact same as before, but did not run the respin. No issues, killer card is working no problem. I've manually installed all my drivers (nvidia and whatnot).

I'm not sure if the respin is installing an update for the card or not, but it's breaking the wifi for many people on 18.04 and 19.04.

**Comment by JackHack96** [comment]
Uhm, this is very strange! I'm currently running 19.04 (with CUDA) + my own respin script.
The xps-tweaks.sh simply downloads latest firmware for our WiFi card. If you have time, you could simply comment out the rows downloading the firmware (comment rows 163-165)

**Comment by roushrsh** [comment]
Strange. The display error only occurs after upgrading to 430 and according to someone who contacted dell it's a known issue and their only solution is a clean install. I'm not sure what the precursor is to cause it.

As for the wifi, that is what I did and it's so far working fine, so it is most definitely the driver causing the issue. I had before downgraded to the previous driver version in an attempt to fix it and the issue persisted. Maybe I should have tried a much older version.

I hope this helps anyone else who runs into these issues.

**Comment by JackHack96** [comment]
I'm sorry I can't understand what is causing the issue...
The weird thing is that a lot of other users upgraded to 19.04 without problems (apart from the random freeze experienced with the nVidia driver).
I myself use also CUDA (for 18.10) for the University

**Comment by roushrsh** [comment]
I just wanted to say changing wifi cards to 9260 works. No surprise there I guess.

**Comment by mnowotnik** [comment]
I've upgraded 18.04 to 19.04 and downloaded additional ath10k driver WLAN.RM.4.4.1-00140-QCARMSWPZ-1. The connection stopped dropping constantly. So far so good (knock on the wood).

**Comment by aidanthewiz** [comment]
I’ve always had issues with the killer wireless card, I upgraded to intel’s latest AX200 WiFi card instead of the 9260. It works well after installing the latest 5.2 kernel and corresponding drivers from intel. The script never caused me issues with the killer card, it was always the killer card that caused the issues on both windows and Ubuntu for me.

**Comment by JackHack96** [comment]
Intel is known for making very good network cards, but am I the only one who never had a problem with Killer cards?

**Comment by aidanthewiz** [comment]
My GUESS is that killer does in fact make good cards, but they either have a bad manufacturing process, bad quality control, and definitely not the best drivers. Intel seems to have it down to a science, never had an issue with an intel card dropping or having bad performance. Killer is just smaller and probably doesn’t have the same resources available to make almost every chip perfect or make quality drivers.

**Comment by mnowotnik** [comment]
An update: 
I've replaced Killer with Intel AX200. It works great. However, I had to upgrade kernel to 5.1+ and download newest drivers for Intel from [linux firmware git tree](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/).

**Comment by kangasbros** [comment]
I had wifi problems appearing again after upgrading to 19.10. Finally did this:

sudo tee /etc/modprobe.d/blacklist-ideapad.conf <<< "blacklist ideapad_laptop"

Source: https://askubuntu.com/questions/893384/wifi-doesnt-work-on-fresh-ubuntu-16-04

And now seems to work. For sure this problem is annoying. And difficult to find solutions that work.
