### ISSUE TITLE
Issues after Ubuntu 18.04 kernel update to 5.0

### ISSUE THREAD

**Issue by nikic** [JackHack96/dell-xps-9570-ubuntu-respin#107]
Looks like the 5.0.0-23 kernel has been rolled out on Ubuntu 18.04 recently. A couple of issues I've observed on XPS 9570:

 * Sensors apart from coretemp are missing. In particular acpitz-virtual-0, ath10k_hwmon-pci-3b00 and pch_cannonlake-virtual-0 for me.
 * Thermal management seems to be *much* worse, with fans being quite lively and sometimes spinning up very briefly.
 * External monitor at 4K resolution (HDMI2, Intel graphics) gives a black screen. Explicitly specifying resolution *and* refresh rate with `xrandr` works though. I'm not sure how that differs from the default behavior.

**Comment by JackHack96** [comment]
I'm still on 5.0.0-15, I can't grab 5.0.0-23, maybe they still have to update the mirrors in Italy

**Comment by enovella** [comment]
No issues on:

`Linux xps 5.0.0-24-generic #25~18.04.1-Ubuntu SMP Tue Jul 30 15:03:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by nikic** [comment]
Thanks for checking! Probably something went wrong during the update for me in particular then (I can reliably reproduce the issues by switching the kernel version on startup). Will have to look closer into what happened.

**Comment by mtytula** [comment]
This problem still appears on 18.04 LTS.
