### ISSUE TITLE
Dell XPS 7590 Ubuntu 19.04

### ISSUE THREAD

**Issue by Globegitter** [JackHack96/dell-xps-9570-ubuntu-respin#108]
I just got my new Dell model and installed Ubuntu 19.04 - apart from issues with the wifi driver (Killer 1650 driver was only added in linux 5.1 and some fixes in 5.2) it all worked out of the box smoothly and also my wifi is working again.

So do you know if I can still run this tweaks script here? I should probably uncomment https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/blob/master/xps-tweaks.sh#L162-L165 but otherwise would you expect it to just work? I am also happy to provide some feedback once I tried it out.

**Comment by Globegitter** [comment]
Ok I ran the script without installing the wifi drivers and ended up with a black screen on reboot. I uninstalled the nvidia and intel drivers but that did not help. I also noticed a line appearing `Possible missing firmware ... for module i915` so I revereted that change and I also noticed that the `etc/default/grub` file was empty and there was a `grup.backup-prime-select` or similar. So I reverted that. After that I could restart again. So I am not sure what exactly is messing up the system here but if anyone has any idea it would be great to get this working properly.

**Comment by JackHack96** [comment]
Sorry for the late response. Well, I can't test the script myself, it requires a lot of trial-and-error (I spent two days installing and reinstalling on my 9570 before having a first working version).

It should work though

**Comment by Globegitter** [comment]
Yeah no worries that makes a lot of sense. Thanks for the response though, I will keep this updated as I make progress.

**Comment by Globegitter** [comment]
Installed the nvidia drivers again and all is fine. So that was not the issue. One issue I am still having strangely thoug that `prime-select query` is only showing nvidia. So somehow the intel card is not detected properly still.

**Comment by JackHack96** [comment]
Maybe the Intel card flags are disturbing... IDK

**Comment by rgarrigue** [comment]
Hey @GlobeGitter, I've a question for you. Do you have the latest 2019 XPS ? I bought mine this summer, Dell website advertising a new XPS hence the "2019". 
If yes I'm wondering how you installed Ubuntu ? Disabling secureboot, fast boot and booting with `nomodeset` or `acpi=off` ? I'm fighting with this myself and ended up with `grub-efi-amd64-signed failed to install`, and I'm wondering why

**Comment by JackHack96** [comment]
> Hey @Globegitter, I've a question for you. Do you have the latest 2019 XPS ? I bought mine this summer, Dell website advertising a new XPS hence the "2019".
> If yes I'm wondering how you installed Ubuntu ? Disabling secureboot, fast boot and booting with `nomodeset` or `acpi=off` ? I'm fighting with this myself and ended up with `grub-efi-amd64-signed failed to install`, and I'm wondering why

Did you set AHCI for disks in the BIOS?

**Comment by rgarrigue** [comment]
Yes also

**Comment by Globegitter** [comment]
@rgarrigue yeah it is the latest model I have. There where no issues whatsoever to install it. All I did was setting the AHCI in the BIOS, then I installed using the standard Ubuntu 19.04 ISO and the only thing that was not working was the wifi, for which I manually installed the latest firmware (and I think it should be fixed with 19.10).

Nothing else I had to disable as far as I remember. I did end up disabling secure boot as well but I am pretty sure that was just due to nvidia drivers.

But where are you seeing `grub-efi-amd64-signed failed to install`?

**Comment by rgarrigue** [comment]
@Globegitter Around the end of the install process. 

I guess the mistake I made was power it on to check it was working, thus starting the Windows 10, and powering it down the hard way out of lazyness to finish the W10 configuration. It might have locked the UEFI.

So there I am, I've been trying a lot of thing, like ideas from https://bugs.launchpad.net/ubuntu/+source/grub-installer/+bug/1771651, nothing worked so far.

**Comment by rgarrigue** [comment]
So just for the record, I managed to install my laptop using `ubiquity -b` to do so without bootloader, then using Boot Repair to get a functional boot.

**Comment by Globegitter** [comment]
@rgarrigue Great! Have you tried out the xps tweaks script yet?

**Comment by rgarrigue** [comment]
No. Everything seems fine, I guess I'll read it and cherry pick what might be interesting.

**Comment by Globegitter** [comment]
@rgarrigue If you do I would be curios to hear what worked for you and what you cherry picked.

**Comment by SulemanAhmadd** [comment]
Hey guys, is anyone experiencing cpu thermal throttling on Dell XPS 7590 under ubuntu 19.04?

**Comment by SulemanAhmadd** [comment]
Things are working pretty stable now after the 19.10 update.

**Comment by JackHack96** [comment]
> Things are working pretty stable now after the 19.10 update.

Good to know, I believe Ubuntu 19.10 is good out-of-the-box. Just install TLP and go!

**Comment by Pot-8-O** [comment]
> @rgarrigue yeah it is the latest model I have. There where no issues whatsoever to install it. All I did was setting the AHCI in the BIOS, then I installed using the standard Ubuntu 19.04 ISO and the only thing that was not working was the wifi, for which I manually installed the latest firmware (and I think it should be fixed with 19.10).
> 
> Nothing else I had to disable as far as I remember. I did end up disabling secure boot as well but I am pretty sure that was just due to nvidia drivers.
> 
> But where are you seeing `grub-efi-amd64-signed failed to install`?

Could you tell me how exactly you got the wifi working? It is currently also the only thing not working on my 7590.

**Comment by rgarrigue** [comment]
@Pot-8-O for the wifi see [here](https://support.killernetworking.com/knowledge-base/killer-ax1650-in-debian-ubuntu-16-04/)

**Comment by Pot-8-O** [comment]
@rgarrigue 
I tried this before but without success.
But now I updated my 5.0.x kernel to 5.2.2 and together with these steps it worked.

**Comment by Globegitter** [comment]
@rgarrigue @Pot-8-O @SulemanAhmadd Is any of you having issues with changing the display brightness? When I press Fn+F11/12 I can see the brightness indicator pop up and the bar also changes but nothing happens to the actual brightness of the screen. Are you experiencing the same? I have searched around online and found a few articles but nothing fixed anything.

Also I just reinstalled with Ubuntu 19.10 beta and everything worked really smoothly. It installed the nvidia driver out of the box, I can also see a new option with prime-select, called `on-demand` and wifi also worked out of the box :) Now just the screen brightness left.

**Comment by rgarrigue** [comment]
@Globegitter no issue related to brightness here.

**Comment by Pot-8-O** [comment]
@Globegitter also no brightness issues here

**Comment by Globegitter** [comment]
Hmm, odd. Are you having the OLED screen version? I wonder if it could have something to do with that.

**Comment by SulemanAhmadd** [comment]
@Globegitter Yes, the OLED panel does have issues with changing the brightness setting. 

In order to resolve that I followed the Screen Brightness setup here:
https://github.com/TillmannBerg/Ubuntu-Dell-XPS-15-2019

It allows you to change the screen brightness from the keys, but the display bar will still not have any effect. Secondly, the display settings are not saved when you shutdown the laptop, so you have to change the brightness every time.

**Comment by ferrolho** [comment]
@Globegitter, have you managed to install and use the nvidia drivers?

I also have the Dell XPS 15 7590, and even though the driver shows up under "Additional Drivers" and is selected, it does not seem to load properly:
> ERROR: NVIDIA driver is not loaded

![Screenshot from 2019-10-01 20-04-40](https://user-images.githubusercontent.com/4166093/65992253-c433f200-e486-11e9-907d-b1d11e92d1e8.png)

![Screenshot from 2019-10-01 20-04-57](https://user-images.githubusercontent.com/4166093/65992267-c8f8a600-e486-11e9-91b4-41efff050fc0.png)

**Comment by Globegitter** [comment]
@ferrolho I would recommend to just wait for Ubuntu 19.10 (or go with the beta) and then re-install from scratch. There you can select for the nvidia drivers to be installed with the OS installation.

But also do check if your nvidia graphics card is selected or your intel one, via `prime-select query`.

**Comment by Globegitter** [comment]
@SulemanAhmadd Thanks for that link I will check it out.

**Comment by ferrolho** [comment]
```zsh
➜  ~ prime-select query
nvidia
```

@Globegitter, right. I'll have a try at the beta (official release is in 14 days anyway). Surely I won't need to reinstall from scratch, right?

**Comment by Globegitter** [comment]
@ferrolho I tried to upgrade without reinstalling and then I could not boot up anymore. I have read at a few different places (forums, reddit etc) that between certain ubuntu versions it is safer to reinstall from scratch. I don't have that much experience with it and it might lead to exactly the same result in your case but could be worth trying.

**Comment by Globegitter** [comment]
@ferrolho Also for me the 435 driver is the selected one, have you tried that one?

**Comment by SulemanAhmadd** [comment]
@Globegitter Have you found out any alternate way to change the display brightness?

**Comment by ferrolho** [comment]
> @ferrolho Also for me the 435 driver is the selected one, have you tried that one?

Yes, I have tried both versions. I think I will wait for the 17th to just reinstall 19.10 from scratch and check if that solves the problem. I shall report back here then.

**Comment by Globegitter** [comment]
@SulemanAhmadd Not yet, for me the solution from https://github.com/TillmannBerg/Ubuntu-Dell-XPS-15-2019 works well enough for now.

**Comment by Globegitter** [comment]
@SulemanAhmadd The only other thing I have come across just now is: https://wiki.archlinux.org/index.php/Dell_XPS_15_7590#Backlight - but not given it a try yet.

**Comment by ferrolho** [comment]
> @SulemanAhmadd The only other thing I have come across just now is: https://wiki.archlinux.org/index.php/Dell_XPS_15_7590#Backlight - but not given it a try yet.

I am using that one and it works fine. The only issue with it is if you use it alongside _Night Light_. Does  https://github.com/TillmannBerg/Ubuntu-Dell-XPS-15-2019#screen-brightness-oled work with _Night Light_?

**Comment by ferrolho** [comment]
@Globegitter (and everyone else), **Ubuntu 19.10** has been officially released and I decided to install from scratch. Results:
- _NVIDIA_ drivers were installed without a problem;
- _Wi-Fi_ works out-of-the-box too;
- _Fingerprint scanner_ (?);
- _Brightness_ control is still a problem.

**Comment by Globegitter** [comment]
Yep, I can confirm this experience. Even though it would be nice to have brighntess out of the box I am overall quite happy with the experience now :)

**Comment by naXa777** [comment]
>  I should probably uncomment https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/blob/master/xps-tweaks.sh#L162-L165 but otherwise would you expect it to just work?

I don't understand these lines.

@Globegitter, could you explain why do you think you need to uncomment these lines for your Dell? you have Dell XPS 7590, right?

**Comment by ferrolho** [comment]
@naXa777, there's a bit of confusion here: @Globegitter did not copy the permalink when he wrote his comment in this thread, and now the lines are pointing to a different piece of code. Since his comment has been posted on August 12, and the latest commit in this repos previous to that date is 68ac304dc5606a449a0d856cb7137c2222677efc, the lines which he was originally referring to are: https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/blob/68ac304dc5606a449a0d856cb7137c2222677efc/xps-tweaks.sh#L161-L165.

**Comment by Globegitter** [comment]
@naXa777 yes @ferrolho is correct - sorry about that and thanks for posting the correct lines.

**Comment by pistomat** [comment]
Hey guys, thanks for the tips. I am having trouble getting my display to work. I have the FullHD IPS version.

After several reinstallations of a Ubuntu 18.04 LTS and Ubuntu 19.10 I managed to get it to install with these options:

- `nomodeset` in `/etc/default/grub` settings
- lightdm display manager
- nvidia-driver-435 from Software & Updates - Additional drivers tab

Here is what is weird. I tried running the system on the Intel GPU by running `sudo prime-select intel`. After reboot the `sudo prime-select query` outputs `intel` as expected, `nvidia-smi` fails as expected and `nvidia-settings` shows PRIME-profile in `Intel (Power Savings Mode)` as expected. This leads me to believe the Nvidia GPU is succesfully turned off, yet the built-in display shows heavy artifacts making in unusable most of the time (the other time I experienced something similar was when I fried my GPU on my old desktop). However an external monitor I am using works flawlessly, so what is going on?

I tried running this script after one of the fresh installs, but it booted into black screen so I reinstalled it again.

**Comment by SulemanAhmadd** [comment]
Is any one of you having random freezes on ubuntu 19.10? (They randomly occur and then go away). Feels like the kernel just freezes.

**Comment by sanjayja** [comment]
> > @SulemanAhmadd The only other thing I have come across just now is: https://wiki.archlinux.org/index.php/Dell_XPS_15_7590#Backlight - but not given it a try yet.
> 
> I am using that one and it works fine. The only issue with it is if you use it alongside _Night Light_. Does https://github.com/TillmannBerg/Ubuntu-Dell-XPS-15-2019#screen-brightness-oled work with _Night Light_?

Below link instructions working fine on my Dell_XPS_15_7590.
https://github.com/udifuchs/icc-brightness

**Comment by rmaree** [comment]
Hello all,

Thanks for the different inputs that helped me to install my Dell XPS 7590 Oled using Ubuntu 19.10.

However i'm still experimenting some issues and i'm wondering if anyone has/had the same ones:

1) Suspend is not working. WHen I close the lid and re-open it, everything is freezed, keyboard and touchpad are not working anymore and i have to do a hard shutdown. Also I don't have any option in the GUI to suspend (All entries in /etc/systemd/sleep.conf  are also commented by default). It seems suspend might not be efficient according to https://ubuntuforums.org/showthread.php?t=2429906
Is it ok for you ? 

2) I have some erratic behavior with usb devices, e.g. mouse is not working after a reboot after the login screen (but it works at the login screen), so i have to unplug/replug it to make it work.

3) Brigthness adjustements with xrandr seems to be reset to default bright values on a rather regular basis (like opening an applicaton or plugin a device) and conflicts with night light mode, i'm now considering using icc-brightness (as mentioned before) or eyesome (https://github.com/WinEunuuchs2Unix/eyesome)

4) I'm a bit disappointed by battery life although of course it very much depends on usage. I'm combining tools such as powertop tunables,  laptop-mode, and low brightness, to improve this but i'm often above a discharge rate of 30 watts (as reported by powertop) and around 3 or 4 hours of autonomy. What about yours ?

5) I'm not yet able to detect my Bluetooth devices (Motorola Moto-E Android smartphone, Libratone Zipp speakers). I realized today in a public space i'm detecting some other bluetooth devices, so i'm still investigating.

**Comment by sanjayja** [comment]
For Point 1. I am facing same issue.
For Point 2. I didn't used external mouse, hence not tested.
For Point 3. Although brightness control woking fine using icc-brighteness after login, however for gdm login screen still it is showing in full brightness mode.
Point 4. I am facing same issue as workaround using Vmware Workstation during transist.
Point 5. I tested sennheiser headset hd 4.40 bt bluetooh headset, it is working fine.

**Comment by SulemanAhmadd** [comment]
@rmaree 

1: Follow the instructions on: (https://wiki.archlinux.org/index.php/Dell_XPS_15_7590#Suspend). You need to select the deep variant.

2. Yes, happens to me as well for my ear phones. Have to replug them. Please let me know if anyone finds a solution for this.

3. Same Issue. Looking for a solution.

4. The graphic card update guide at (https://github.com/TillmannBerg/Ubuntu-Dell-XPS-15-2019), does make the power consumption to fluctuate around 12W, but the when the system goes into standby, the GPU "falls off the bus" when waking up and requires hard reset.

5. Works fine for me.

**Comment by aviskase** [comment]
> Is any one of you having random freezes on ubuntu 19.10? (They randomly occur and then go away). 

Yup. Do you use Gnome with XOrg? I've noticed that it's just touchpad (mouse and keyboard probably too), but the environment seems to be ok (I see terminal continue to update). It looks like Gnome/XOrg related problem.

**Comment by aviskase** [comment]
I have two problems, does anyone know how to solve them?
1. With time Gnome eats ~7.7 GB memory
2. Constant lags during scrolling or watching videos&gifs, around every 3sec. They are bearable, but completely unexpected --- my 9 years old laptop never had such problems

**Comment by rgarrigue** [comment]
Hi guys

Just sharing a day of pain : 

- My 19.04 refused to boot after upgrading to 5.0.0-8 (or was it 18 ?) and a network card driver recompilation.
- To get a live environment working (the Test Ubuntu Linux option at boot) on 19.10, I had to edit the start command line `e`, removed `quiet splash` and added `nomodeset modprobe.blacklist=intel_lpss_pci`. Using `acpi=off` ended up with a kernel panic, the default live option ended up freezing after a minute or so, the safe graphic live stuck on a black screen before reaching live
- The live is by default using the free graphic drivers (not the NVidia one now shipped with 19.10, will try those later). Wifi is working. Changing keyboard light is working, changing display light isn't, touchpad is working (wasn't in 18.04). Webcam is working.
- I didn't had the installation problem (UEFI stuff) I mentionned in this topic 4 month ago

Random notes

- LPSS seems related to low power subsystem like touchscreen. I disabled mine in the BIOS anyway, I don't like the feature
- From Freenode IRC #Ubuntu : kernel 5.4.2.1-1 apparently works around this dell xps specific problem, so you can try upgrading to this or a higher kernel version after installation, if needed. https://wiki.archlinux.org/index.php/Dell_XPS_13_2-in-1_(7390)#Intel_LPSS
- ... and possibly related - the 19.10 kernel on the live iso will be older, but the one on the installed system, after updates, should have the patch: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1845584

**Comment by Globegitter** [comment]
@aviskase While I am not having issues, from what I have read Canonical is still working on performance for gnome for Ubuntu 20.04 and 20.10, so hopefully the next two Ubuntu releases should fix these issues. But it might also be worth reporting that somewhere so the Canonical devs can see it.

**Comment by ielkhalloufi** [comment]
Hi, have you guys got the fingerprint working?

The GPU "falls off the bus" was solved by using the wayland server instead.

**Comment by aviskase** [comment]
> @aviskase While I am not having issues, from what I have read Canonical is still working on performance for gnome for Ubuntu 20.04 and 20.10, so hopefully the next two Ubuntu releases should fix these issues. But it might also be worth reporting that somewhere so the Canonical devs can see it.

@Globegitter I found out that it's known issue and the only way around it right now is to periodically restart session (`ALT+F2` and `r`)

**Comment by Phil171** [comment]
Hi, 
This is my first answer on this forum, be indulgent for spelling or grammar mistakes and silly questions, I do not master English perfectly ... That's the problem to be French...

I'm the (very) happy owner of a Dell XPS 15 7590 (2020) with i7-9750H, 16Go RAM, 512Go SSD M2 Nvme, FHD matt and non sensitive display in dual boot with Win10 and Xubuntu 18.04 up to date. 

Just to say that with V18.04, I don't have ANY problem really and just had have to solve power management by installing TLP and Powertop and modify /etc/tlp.conf to be happy by creating a service named "powertop.service".
`sudo nano /etc/systemd/system/powertop.service`
Filled with :
`[Unit]
Description=Powertop tunings

[Service]
Type=oneshot
ExecStart=/usr/sbin/powertop --auto-tune

[Install]
WantedBy=multi-user.target`
And activated with : 
` systemctl enable powertop.service`
 
My computer consumes approximately 8.5 - 10 watts, whether in AC or on battery.
I uninstalled the Nvidia drivers, I use the Intel card (mainly office and web use) and I use the " Nouveau" drivers, I tried Prime but uninstalled it because it did not work properly when restarted from the computer.
My next problem will to find and use fingerprint drivers ( Model HTK32, ID 27c6:5395 from Goodix) , it seems they are used on Android and Gnome but I'm not sure.

**Comment by thewally** [comment]
> @SulemanAhmadd Not yet, for me the solution from https://github.com/TillmannBerg/Ubuntu-Dell-XPS-15-2019 works well enough for now.

Here you can find a fork of this project. https://github.com/MuDiAhmed/Ubuntu-Dell-XPS-15-2019 with this fork you can fix:
- Killer Wifi driver
- CPU power management
- Changing brightness of OLED screen with brightness keys
- Suspend Draining battery fas

**Comment by aviskase** [comment]
The repo owner updated scripts for 20.04. Did anyone upgrade their 7590? I found some disturbing posts about bad performance after the upgrade, and I wonder, did the same happen to those who used this repo's instructions?
