### ISSUE TITLE
bad audio quality with bluetooth headphones

### ISSUE THREAD

**Issue by grybouilli** [JackHack96/dell-xps-9570-ubuntu-respin#109]
Hello,
I've just noticed that using my headphones through bluetooth connexion completely kills the audio quality. It sounds like it's coming out of a radio somehow.
I tried different sound profiles but none seem to make it better, has any one any idea?

**Comment by JackHack96** [comment]
Ehm, sorry that's too generic. I still haven't tried to connect BT headphones because I don't own any, but other users reported they have absolutely no issues with it.

**Comment by mvandewouw** [comment]
When headset connected go to settings>sound. Select your headset, and on bottem select profile: High Fidelity Playback (A2DP Sink)
