### ISSUE TITLE
Everything appears tiny after running xps-tweaks.sh

### ISSUE THREAD

**Issue by ambersariya** [JackHack96/dell-xps-9570-ubuntu-respin#110]
Not sure how could I fix this but after running the script and successfully rebooting, everything appears to be tiny. Graphics are switched over from Nvidia to Intel as expected.

However, display scaling is set to 100% which was previously set to 200%. When I change this and reboot, everything returns back to scale 100%. Did anyone experience and hopefully fix this issue?

**Comment by Artlist-creator** [comment]
Do you use wayland or xserver for your device?
if you use xserver type in terminal with sudo privilege:
`sudo -s`
then
`xrandr --output DP1 --mode 3840x2160 --scale 2x2`
This would change the output DP1 (internal screen) to 3840x2160 with 200% scaling
And then type 
`xdotool search --class xterm behave %@ focus exec xrandr`
To automate this
For more information go to:
[http://manpages.ubuntu.com/manpages/trusty/man1/xdotool.1.html](url)
[https://askubuntu.com/questions/281509/how-do-i-change-the-screen-resolution-using-ubuntu-command-line/398740#398740](url)

**Comment by ambersariya** [comment]
I use XServer, I had a couple of issues using Wayland. 

For example, while using Microsoft Teams (https://github.com/IsmaelMartinez/teams-for-linux), the screen sharing option would just not work and I have a double monitor setup at work where the external displays would be ok but laptop screen would be somewhat blurry no matter what the scale value is. 

Thank you for your help, the scaling works ok after every reboot now but I have to change the display order every time. I shall close this issue for now
