### ISSUE TITLE
WiFi breaks

### ISSUE THREAD

**Issue by viliwonka** [JackHack96/dell-xps-9570-ubuntu-respin#113]
Hello, the WiFi breaks after running the post-install script. The WiFi was working fine before. 
Everything else works!

**Comment by JackHack96** [comment]
Please run `sudo apt install --reinstall linux-firmware`.
If you can't connect to the internet, use your smartphone as a USB hotspot

**Comment by viliwonka** [comment]
Hey, I solved it by copying the files (that were rm-ed in script) from live linux back to my PC (same relative paths).

Thanks for command though, I saved it :). Btw yes, WiFi/Ethernet breaks.
