### ISSUE TITLE
10-prime-offload.conf not found

### ISSUE THREAD

**Issue by ns3284** [JackHack96/dell-xps-9570-ubuntu-respin#116]
After running the Prime Offload, the script attempts to copy the 10-prime-offload.conf file, but it is not found.

**Comment by szkocot** [comment]
For now you have to download this file from this project and copy to directory from which you are running the script or clone the whole project and It should be fine.
The easy way to fix it would be to add checking step if the .conf file is available and otherwise download it.

**Comment by JackHack96** [comment]
Ops, going to fix this now.

**Comment by ns3284** [comment]
Just realized that it is cause I executed the file, but needed to first copy that file. Perhaps doing a wget/curl on the file from the repo to the location to be copied to?

**Comment by JackHack96** [comment]
Done!
