### ISSUE TITLE
CPU package never goes in efficient C states after suspend-resume

### ISSUE THREAD

**Issue by IvanBernatovic** [JackHack96/dell-xps-9570-ubuntu-respin#117]
Hi, I'm not sure this is the right place to post this but maybe somebody has an idea. This is tested on a Dell XPS 15 9570 FullHD i7 version, with a fresh installation of Ubuntu Budgie 18.04 and with xps-tweaks.sh script applied. 

Basically, I noticed that my CPU temperatures are higher when resuming after suspend. After turning on the laptop CPU temps are around 36-39 on idle (tested for few minutes). After first suspend/resume the CPU temps go to around 46-52 with fans always spinning as a result. Power consumption goes up from around 6-7W to around 15W after suspend.
 All of this is tested with no additional programs launched (idle). 

After inspecting powertop Idle stats tab I noticed that CPU package never goes into more efficient C states (C2 and upwards), while before suspend CPU package was mostly residing in C8 state. Screenshots below:

Idle stats **before** suspend:
![Screenshot from 2019-09-19 10-29-48](https://user-images.githubusercontent.com/11651980/65230482-39d6b000-dace-11e9-9afb-8de85944a12d.png)

Idle stats **after** suspend:
![Screenshot from 2019-09-19 10-56-44](https://user-images.githubusercontent.com/11651980/65230517-4a872600-dace-11e9-97cd-6afb2484c8d2.png)

I don't even know where to start since there are not a lot of instructions how to deal with C states issues on Linux. Do you guys have a similar issue and do you know where to start?

**Comment by IvanBernatovic** [comment]
After some research, I found out that the issue is in the touchpad. For some reason, it's preventing the CPU to go in lower power states and the only way to fix this is to disable the touchpad. Immediately after disabling it the CPU went into lower power states and power consumption and temperatures went lower. 

After some time I enabled touchpad again but the CPU was still able to go to lower power states which means that there is a bug with touchpad and wake up/resume on Linux.

**Comment by JackHack96** [comment]
Well, to be fair, I always noticed a little higher power consumption after resume, but not that big, max 8W with Intel card...

Anyway, good to know it's the touchpad, maybe it's something related to libinput, idk. Disabling and enabling touchpad is a good workaround for now...

**Comment by IvanBernatovic** [comment]
The issue is also documented [here](https://askubuntu.com/questions/1138642/ubuntu-18-04-drains-battery-very-fast-after-wake-up-from-a-deep-sleep) and [here](https://askubuntu.com/questions/614331/high-number-of-interrupts-on-ubuntu-15-04-on-dell-xps-13-2015-9343). First link references the same issue on same XPS 15 model and the second link references the same issue on Dell XPS 13 that dates back to 2015. 

Maybe it would be wise just to document it on the wiki as a potential issue.

**Comment by JackHack96** [comment]
Done! Closing this issue as I can't solve it personally.
