### ISSUE TITLE
Multiple Monitors Issue

### ISSUE THREAD

**Issue by ukramer** [JackHack96/dell-xps-9570-ubuntu-respin#118]
Hi there,

I ran your tweak script. Thanks for your work.

I have a problem using nvidia gpu with multiple monitors. I use an original Dell docking station and have monitors linked with Display Port.

**Problem:** I cannot connect two external monitors. One external monitor is working perfect.

Connecting the second external monitor during startup ends in a freeze.
Connecting after start up: The monitor is listed in "Displays" Settings of Ubuntu. But I cannot active it. Running the command xrandr --output DP-1-2 --mode 2560x1440 --pos 3840x0 --rotate normal is not working with error: xrandr: Configure crtc 2 failed. When I activate the display in the Display settings, it gets switched off after applying the changes.

I have the driver: nvidia-driver-435 (open source) installed. Tried also with different kernels as I read that there probably is a problem. Now running on 5.2.17-050217-generic.

When changing to terminal (Ctrl + Alt + F2 / F3) all three displays are showing up as mirrors.

Do you probably have an idea what could be the issue? Maybe something with the xorg configuration? I tried to edit your config file by using dGPU for external monitors (just replaced iGPU with dGPU) => without success and then removed the full configuration but then the system didn't start up. 
I even cannot find a default xorg.conf. Thanks for any advice.

**Comment by JackHack96** [comment]
You can't find the default xorg.conf simply because there isn't one. Everything is determined dynamically at runtime, by `gpu-manager`.
That said, I can't test it because I don't have the Dell dock nor I have other monitors. At school, where we use projectors, I always had troubles with some of them even not recognizing HDMI (god bless VGA), but in that I'm not sure it it's something of my laptop or the projectors, given that a lot of professors have troubles too..

**Comment by hhe** [comment]
For what it's worth, I've found the Dell docking station to be generally unreliable and would randomly kill video output on one or more screens, as well as the USB ports. What eventually worked to me was switching to the [CalDigit TS3 Plus](https://shop.caldigit.com/us/index.php?route=product/category&path=88). And no they are not paying me to say that :)
