### ISSUE TITLE
Support for Ubuntu 19.10

### ISSUE THREAD

**Issue by fabianbees** [JackHack96/dell-xps-9570-ubuntu-respin#119]
Enable Support for Ubuntu 19.10 in the Script

**Comment by JackHack96** [comment]
I have been using 19.10 for a week now, I feel it's quite stable. The script is just ok, I just add eoan to the supported releases :)

**Comment by wibotwi** [comment]
Script adds ppa:aplattner/ppa which does not exist for 19.10
Is that ppa needed? Prime on-load works fine in Ubuntu 19.10.
