### ISSUE TITLE
Fan speed is immense

### ISSUE THREAD

**Issue by xban1x** [JackHack96/dell-xps-9570-ubuntu-respin#12]
I am playing a relatively non-intensive browser game. Tribal Wars 2. Now I figured that if I play from intel it should help keep the laptop cooler and fan less noisy but nope it makes it run 100%. Yet when using Nvidia it is the same or even worse. Any idea how to control the Nvidia and the fans better so I would get a less noisy laptop?

**Comment by JackHack96** [comment]
Yeah please try running `systemctl disable nvidia-fallback.
