### ISSUE TITLE
Fn + F11 F12 for bightness not working

### ISSUE THREAD

**Issue by sahlouls** [JackHack96/dell-xps-9570-ubuntu-respin#120]
Hi,
After applying the script (maybe before), I can't adjust the brightness anymore.
Any help on how to fix it ?
Thyanks

**Comment by JackHack96** [comment]
This is not related to the script, because it doesn't do anything related to hotkeys.
Does the brightness slider in the settings works?

**Comment by sahlouls** [comment]
The slider in the settings is not working :disappointed:

**Comment by floturcocantsee** [comment]
Are you using the 9570 or  the new OLED model? OLED panels aren't controlled by the xbacklight daemon and need an external tool.

**Comment by sahlouls** [comment]
@floturcocantsee no OLED screen

**Comment by JackHack96** [comment]
I can't reproduce the bug unfortunately, I have the 9570 with FHD screen...

**Comment by notthebee** [comment]
I found that you can still control brightness with `brightnessctl `(available in Ubuntu repositories).
What I personally did is map brightness control keys to `brightnessctl s 2000-` and `brightnessctl s +2000` respectively.
However, by default GNOME doesn't allow mapping media keys, so you will have to change a couple of value in dconf.

**Comment by ababino** [comment]
Hi,
Same problem here with Ubuntu 19.04. I solved it adding `acpi_backlight=native` and `thinkpad-acpi.brightness_enable=1` to `GRUB_CMDLINE_LINUX_DEFAULT`. Don't forget to run `sudo update-grub` for the changes to take effect.

I hope this is useful.

**Comment by JackHack96** [comment]
> Hi,
> Same problem here with Ubuntu 19.04. I solved it adding `acpi_backlight=native` and `thinkpad-acpi.brightness_enable=1` to `GRUB_CMDLINE_LINUX_DEFAULT`. Don't forget to run `sudo update-grub` for the changes to take effect.
> 
> I hope this is useful.

Thank you, I'll report it in the wiki!

**Comment by sahlouls** [comment]
Thanks @ababino, with this config, the brightness control is working again.
Thanks @JackHack96 for updating the wiki page !
