### ISSUE TITLE
Upgrading from 18.04 to 19.10

### ISSUE THREAD

**Issue by DonkeyShot21** [JackHack96/dell-xps-9570-ubuntu-respin#122]
Hi everybody,
I have installed the respun ISO (Ubuntu 18.04) some time ago and I am wondering what would happen if I upgraded to Ubuntu 19.10 with dist-upgrade.

Someone who tried it can please report if it worked or it breaks everything? I need to work with my computer so I cannot take too many risks, but still I want to try the new features

**Comment by JackHack96** [comment]
I personally didn't upgrade, just wiped for both 19.04 and 19.10 (I have a separate /home partition so I don't loose settings and documents).
I have a friend who upgraded without problems, so I guess it should work.
Be aware though that you can't upgrade directly from 18.04 to 19.10 through `sudo do-release-upgrade`, you would have first to upgrade to the others.

I understand it takes time, so my advice is to just wait for 20.04 (it'll be possible to update 18.04 directly) or if you absolutely want to try new features backup your personal data and do a clean install.

**Comment by DonkeyShot21** [comment]
Ok, I understand, thanks for the clarification, I think I will wait for 20.04 as you suggested.

**Comment by henrikekblad** [comment]
I've upgraded to 19.10 and the system actually feels more stable for me so far. I haven't tried nvidia gpu though, as the latest kernels doesn't seem to support it...

**Comment by JackHack96** [comment]
> I've upgraded to 19.10 and the system actually feels more stable for me so far. I haven't tried nvidia gpu though, as the latest kernels doesn't seem to support it...

As I said, I'm also using 19.10 because it has a lot of performance improvements for GNOME. For the nVidia, I'm using nvidia driver 440

**Comment by DonkeyShot21** [comment]
Yes, GNOME is laggy on 18.04, I am currently using KDE Plasma.
See https://discourse.ubuntu.com/t/boosting-the-real-time-performance-of-gnome-shell-3-34-in-ubuntu-19-10/13095
