### ISSUE TITLE
nvidia-smi No devices were found

### ISSUE THREAD

**Issue by YantianZha** [JackHack96/dell-xps-9570-ubuntu-respin#125]
I have strictly followed the post-installation step. After rebooting, I input "nvidia-smi" command in terminal and got "No devices were found". Any suggestions? Thanks!
![1](https://user-images.githubusercontent.com/9017839/73414781-e6773880-42dd-11ea-8fb9-306370634252.png)

**Comment by dvatsal** [comment]
I am facing same issue

**Comment by YantianZha** [comment]
Maybe we should use an older version of Ubuntu 18.04 (e.g. 18.04.1 instead of 18.04.3)? https://devtalk.nvidia.com/default/topic/1063087/nvidia-driver-418-not-loading-on-ubuntu-18-04-3/

**Comment by JackHack96** [comment]
Try uninstalling the 435 driver and install the 440

**Comment by YantianZha** [comment]
Nothing has been changed. What I did was:
sudo apt-get purge ^nvidia- // uninstall currently installed 435 driver
sudo add-apt-repository -y ppa:graphics-drivers/ppa
sudo apt -y install nvidia-driver-440 nvidia-settings
reboot

**Comment by JackHack96** [comment]
Are you sure that the nVidia profile has been selected?
`sudo prime-select nvidia` + reboot should do the trick. I had this working since 18.04 :thinking:

**Comment by YantianZha** [comment]
Yes I'm sure. I also did a reinstall of ubuntu 18.04, and downloaded the latest version of your script (which also has the command of 440 driver install) to upgrade the system. Still shows "no devices were found".
![Screenshot from 2020-02-02 15-42-20](https://user-images.githubusercontent.com/9017839/73615088-1884e500-45d3-11ea-88cf-d90942428a07.png)

**Comment by JackHack96** [comment]
Uhm... This is strange...
Sincerely I don't know what to do, maybe you could try deleting `/etc/X11/xorg.conf.d/10-prime-offload.conf` and `/etc/modprobe.d/nvidia-drm.conf`, then launch `sudo dpkg-reconfigure nvidia-dkms-440`.

This will rebuild the driver and the initramfs, without any customization (as if installed just from the driver utility found in Ubuntu)

**Comment by YantianZha** [comment]
@JackHack96 Could you let me know your BIOS version? Thanks!

**Comment by JackHack96** [comment]
I'm running of BIOS 1.14.
Yesterday I saw there's a new release available, I still have to install it though.

**Comment by JackHack96** [comment]
I installed the latest BIOS, 1.15, and while I'm experiencing high power consumption due to the nVidia card being active (not related to the BIOS itself), I can use it without problems.
I even tried removing the customizations for running the dedicated card on-demand and switched to stock configuration, and even in that case I can switch without problems using `prime-select`.

I'm sorry but at this point I can't help you further, it could be something else which is interfering with the driver, I don't know...

**Comment by YantianZha** [comment]
Thanks @JackHack96 ! Sorry for the late reply. I am in the middle of a project and cannot run the risk of upgrading the BIOS. I will get back to you once I tried. Thanks!

**Comment by Romcol** [comment]
Hi @YantianZha !

I had the same issue as you. I had to remove the offloading script (see https://forums.developer.nvidia.com/t/geforce-gtx-1050-ti-driver-installed-on-ubuntu-19-10-but-not-used/117588).

Also I experiences screen tearing, I had to apply this patch : https://forums.developer.nvidia.com/t/geforce-gtx-1050-ti-driver-installed-on-ubuntu-19-10-but-not-used/117588 .

Hope this helps! :+1:

**Comment by JackHack96** [comment]
I've fresh-installed Ubuntu 20.04 a week ago and I've already updated the tweak script.
The VERY good news is that the tweaks needed for making the system to work good are very minimal this time, as finally Ubuntu will always install the latest graphics drivers available.
The other good news is that now GNOME has a native option for launching with dedicated graphics! So no more terminals with launching commands! :D

**Comment by YantianZha** [comment]
Hello @Romcol 

I tried your solution of removing /etc/X11/xorg.conf.d/10-prime-offload.conf, but it did not work for me. After running nvidia-smi I still see the "No devices were found" message. I also tried to switch to the Intel graphics card and switch back again. Thanks anyway!

**Comment by Romcol** [comment]
@YantianZha I would advice to completely retinstall the driver making sure not to include the offloading script. If that fails you should post a bug report log file to the nvidia forum, they can help you, they usually reply fast :+1:

**Comment by YantianZha** [comment]
Thanks @Romcol !
