### ISSUE TITLE
tlp is not installed by default in ubuntu 19.10 

### ISSUE THREAD

**Issue by robaru** [JackHack96/dell-xps-9570-ubuntu-respin#126]
Hi!
Can I ask why tlp is not installed by default when the script runs on Ubuntu 19.10?

Many thanks,
Roberto

**Comment by JackHack96** [comment]
Because the last time I updated the script the official linrunner PPA was not available for Eoan (though I noticed that TLP can also be installed from the official repo).

Fixed now :)

**Comment by robaru** [comment]
thank you! :)
