### ISSUE TITLE
high CPU use because of kworkers and dock DA200

### ISSUE THREAD

**Issue by robaru** [JackHack96/dell-xps-9570-ubuntu-respin#127]
Hi everyone,
I would suggest a solution that I've found useful for myself. I am currently running Ubuntu 19.04 on the XPS 9570 with all the tweaks proposed. 

I experienced 100% CPU use because of kworker's processes. After some test and web search I've found that this was due because of high load of interrupts. The only difference with the standard configuration is that I am using the dock DA200 through the USB-C port. At this external device I connect the ethernet cable and the usb dongle for mouse and keyboard. 

Since the CPU hogging required to reboot the laptop quite often I've tried different solutions proposed around the web. The best one is proposed here: https://askubuntu.com/questions/1044872/ubuntu-16-04-kworker-using-high-cpu-constantly

The general idea is to disable the USB auto-suspend feature from the grub options. To do this just edit  /etc/default/grub and add
`GRUB_CMDLINE_LINUX_DEFAULT="<existing stuff> usbcore.autosuspend=-1"`
and the update the grub with 
`sudo update-grub`

I am using this solution for a couple of days and up to now the hogging didn't show up! 

Hope that this can be useful  also for other people!

**Comment by robaru** [comment]
There is still an interrupt's issue related when waking up after sleeping. This time is related to the touchpad. 
To solve that I'm trying this solution [here](https://gitlab.freedesktop.org/libinput/libinput/issues/263#note_147818)
`sudo rmmod i2c_hid
sudo modprobe i2c_hid`

**Comment by JackHack96** [comment]
Uhm, this is a rather specific hardware issue. I'll add it in the wiki :)
