### ISSUE TITLE
Nvidia Offloading not working

### ISSUE THREAD

**Issue by jiyojolly** [JackHack96/dell-xps-9570-ubuntu-respin#130]
I run a fresh install of Ubuntu 18.04 on my Dell XPS 15 9570 and I ran the script to set up everything. 
After that, I tried the Nvidia offloading (dynamic switching) feature to run an application on the GPU but it seems to not work. 
I used the command `prime` to offload the application to GPU. 
![image](https://user-images.githubusercontent.com/11443240/80712979-5e891080-8b10-11ea-9635-49a4ddbd6cf2.png)
I also don't seem to have the Nvidia on-demand option available too as shown above.
Please let me know what I can do to fix this.

**Comment by JackHack96** [comment]
What driver version are you using? It should be 440 but could you check it please?
I suspect something went wrong during the script execution...

**Comment by jiyojolly** [comment]
I am using 440. I tried running the script twice. It seems to execute without any problems.

**Comment by smilemango** [comment]
I had same problem. But, now I upgraded to 20.04.
It works well without any additional patch

**Comment by jiyojolly** [comment]
> I had same problem. But, now I upgraded to 20.04.
> It works well without any additional patch

I think upgrading to 19.1 or 20.04 would be a fix, but I am stuck at 18.04 due to the nature of my work. I have to run ROS Melodic & CARLA simulator which is compatible only with ubuntu 18.04. Hence why I am trying to get it working on 18.04.

**Comment by JackHack96** [comment]
I'm out of ideas sincerely, the hybrid option should come anyway with the correct version of `nvidia-settings` v=>435, even if it's not configured...

**Comment by jebron** [comment]
I had the same problem with a new i9 7590, on Nvidia 440 the power saving features of this script and prime-select would not work.  I reverted back to 435 and everything works wonderfully.
