### ISSUE TITLE
Details missing

### ISSUE THREAD

**Issue by sursu** [JackHack96/dell-xps-9570-ubuntu-respin#133]
It would be good if the fixes explained which issues they are solving.

For instance. I have an issue with the Atheros Killer: often when I boot the system it takes about 30s for the wifi to start working.

I am not sure your proposed solution fixes my issue or does something else.

**Comment by JackHack96** [comment]
Here they are:
https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/wiki

Actually, nothing is touched for the WiFi card. If you search a bit you see there are a lot of users that complains about the Killer card. I have a friend who directly substituted it with a 20€ one from Intel...
