### ISSUE TITLE
Goodix fingerprint driver released because of the new XPS models

### ISSUE THREAD

**Issue by p-kostic** [JackHack96/dell-xps-9570-ubuntu-respin#135]
With the new XPS model, Goodix was forced to release a driver for Linux. There's now a fingerprint driver available here

http://dell.archive.canonical.com/updates/pool/public/libf/libfprint-2-tod1-goodix/

And it can be installed on Ubuntu 20.04 with

```shell
sudo dpkg -i libfprint-2-tod1-goodix_0.0.4-0ubuntu1somerville1_amd64.deb
```
After rebooting, you can register your fingerprint from the terminal with 
```shell
fprintd-enroll
```

Haven't tried this yet or seen any people using this with GDM. It's possible that there's not more involved than the above. 

If this is tried and tested by any maintainer of this repo for the 9570, maybe add it to `xps-tweaks.sh`?

**EDIT:**
Some people on the /r/Dell subreddit have been trying to get it working recently with no reported success for the 9570. Worth looking into further?

https://www.reddit.com/r/Dell/comments/hq3kf3/xps_13_fingerprint_drivers_are_here/

### References
https://wiki.archlinux.org/index.php/Fprint

**Comment by JackHack96** [comment]
Going to try this, looks interesting :)

**Comment by Zerquix18** [comment]
Tried but couldn't get it working. I have the 9570 with `ID 27c6:5395 Shenzhen Goodix Technology Co.,Ltd. Fingerprint Reader` and the driver is installed but `fprintd-enroll` says no devices available.

**Comment by mechevarria** [comment]
Still is not working. The same model of reader is in the Dell Precision 5540, running `bash
lsusb` returns `Bus 001 Device 002: ID 27c6:5395 Shenzhen Goodix Technology Co.,Ltd. Fingerprint Reader`

I created a new file called **61-libfprint-2-tod1-goodix.rules** in `/etc/udev/rules.d` with the following

```bash
# Goodix Fingerprint Sensor
SUBSYSTEM=="usb", ATTRS{idVendor}=="27c6", ATTRS{idProduct}=="5395", ATTRS{dev}=="*", TEST=="power/control", ATTR{power/control}="auto", MODE="0660", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="27c6", ATTRS{idProduct}=="5395", ENV{LIBFPRINT_DRIVER}="Goodix Fingerprint Sensor"
```

No luck

**Comment by JackHack96** [comment]
I gave up on trying it too :(
We have been left out from the party unfortunately :(

**Comment by Pascal1812** [comment]
Same issues, i tried that command lines but still not working.
It sees the driver but it's not working.
I think the goodix driver is not yet supported by Linux
