### ISSUE TITLE
nouveau loaded even if prime-select intel is set

### ISSUE THREAD

**Issue by rjloura** [JackHack96/dell-xps-9570-ubuntu-respin#16]
I ran `xps-tweaks.sh` and I noticed that after the nvidia driver was installed and `prime-select` set to `intel` the nouveau driver was still loaded.  I was also getting a much higher idle power usage than before I installed the nvidia driver (~15W vs a previous ~6W as measured by powertop).  I believe that even though the laptop is using the intel on board graphics, the nouveau driver must be doing something with the dGPU.

To confirm, with `intel` selected check:
```
lsmod | grep nouveau
```

From reading [this](https://gist.github.com/tomwwright/f88e2ddb344cf99f299935e1312da880#gistcomment-266397), I found that if I run the following and then reboot, the nouveau driver is not loaded and my on battery idle power consumption dropped back to 6W.
```
systemctl disable nvidia-fallback
```

Consider adding this to the` xps-tweaks.sh` script.

**Comment by JackHack96** [comment]
Thank you, I'll add it ;)
