### ISSUE TITLE
Permission Denied Errors When Re-Spinning

### ISSUE THREAD

**Issue by apahne** [JackHack96/dell-xps-9570-ubuntu-respin#18]
Tried to re-spind (on Ubuntu 18.04.1)

`dell-xps-9570-ubuntu-respin master ➜  ./build.sh ubuntu-18.04-desktop-amd64.iso 
[sudo] password for andy: 
Extracting ISO ...
./isorespin.sh: line 1982: cd: /home/andy/tmp/dell-xps-9570-ubuntu-respin/isorespin: Permission denied
Parallel unsquashfs: Using 12 processors
139912 inodes (156845 blocks) to write

[===========================================================================================|] 156845/156845 100%

created 112482 files
created 16964 directories
created 27397 symlinks
created 7 devices
created 0 fifos
Extracting isorespin files ...
./isorespin.sh: line 2018: cd: /home/andy/tmp/dell-xps-9570-ubuntu-respin/isorespin: Permission denied
Updating bootloader/bootmanager ...
./isorespin.sh: line 3092: cd: /home/andy/tmp/dell-xps-9570-ubuntu-respin/isorespin: Permission denied
./isorespin.sh: line 2966: cd: /home/andy/tmp/dell-xps-9570-ubuntu-respin/isorespin: Permission denied
cp: cannot stat 'grub_bootia32.efi': No such file or directory
cp: cannot stat 'efi_bootia32.efi': No such file or directory
Adding repositories ...
./isorespin.sh: line 2274: cd: /home/andy/tmp/dell-xps-9570-ubuntu-respin/isorespin: Permission denied
Installing packages ...
./isorespin.sh: line 2536: cd: /home/andy/tmp/dell-xps-9570-ubuntu-respin/isorespin: Permission denied
cat: iso-chroot/usr/src/.package.missing: Permission denied
./isorespin.sh: Package '' not found.
`

The log:
`Script './isorespin.sh' called with '-i ubuntu-18.04-desktop-amd64.iso -r ppa:graphics-drivers/ppa -r ppa:linrunner/tlp -p thermald tlp tlp-rdw powertop nvidia-driver-396 nvidia-prime bbswitch-dkms pciutils va-driver-all vainfo libva2 gstreamer1.0-libav gstreamer1.0-vaapi -f wrapper-network.sh -f wrapper-nvidia.sh -f wrapper-powertop.sh -f update-packages.sh -f services/gpuoff.service -f services/powertop.service -c wrapper-network.sh -c wrapper-nvidia.sh -c wrapper-powertop.sh -c update-packages.sh -g quiet acpi_rev_override=1 acpi_osi=Linux scsi_mod.use_blk_mq=1 nouveau.modeset=0 nouveau.runpm=0' ...
Work directory 'isorespin' used ...
ISO '/home/andy/tmp/dell-xps-9570-ubuntu-respin/ubuntu-18.04-desktop-amd64.iso' respun ...
Kernel boot parameters 'quiet acpi_rev_override=1 acpi_osi=Linux scsi_mod.use_blk_mq=1 nouveau.modeset=0 nouveau.runpm=0' added ...
Bootloader 'GRUB' added ...
Repository 'ppa:graphics-drivers/ppa' added ...
Repository 'ppa:linrunner/tlp' added ...
Package '' not found.
`

**Comment by JackHack96** [comment]
The issue should be fixed now
