### ISSUE TITLE
Installer crashes during partitioning

### ISSUE THREAD

**Issue by bajo** [JackHack96/dell-xps-9570-ubuntu-respin#2]
Ubiquity needs to be updated to be at least version 18.04.1 [1]. Can this be added to the script?

[1] https://askubuntu.com/questions/1033179/ubuntu-18-04-installer-crashes-on-dell-xps-15-9560

**Comment by JackHack96** [comment]
When I installed Ubuntu, it didn't crashed, but I wiped everything.
Anyway yes I think I can update it.

**Comment by bajo** [comment]
Great. Thank you.

**Comment by JackHack96** [comment]
Script updated, closing issue
