### ISSUE TITLE
Missing space in build.sh

### ISSUE THREAD

**Issue by sjabasti** [JackHack96/dell-xps-9570-ubuntu-respin#21]
https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/blob/63667a8214cfcba0ab5dbc2a8c14c3425f5614a9/build.sh#L18

build.sh tries to install:
"gstreamer1.0-vaapiintel-microcode" 
Missing space after gstreamer1.0-vaapi

**Comment by JackHack96** [comment]
I'm sorry, now it's correct :)
