### ISSUE TITLE
Fans running now

### ISSUE THREAD

**Issue by andrewmusselman** [JackHack96/dell-xps-9570-ubuntu-respin#25]
After running the xps-tweaks.sh script my fans are running apparently non-stop; is this a known issue?
Is there an "undo" version of the script?

**Comment by JackHack96** [comment]
No, that's not normal (and there's isn't an "undo" script).

Anyway make sure you're running latest kernel (4.18.6), check for the Ukuu utility if you want a simple GUI for managing that.
Then, make sure you're running the latest nVidia drivers from the `graphics-driver` PPA.
It could be that drivers simply didn't successfully installed.

After making sure that all of these requirements are met, check if you're using the Intel card, by using `sudo prime-select query`

**Comment by andrewmusselman** [comment]
Thanks @JackHack96; after a full night's sleep the fans were off this morning :)

Updated the kernel and checked nvidia driver version is 396.54.
