### ISSUE TITLE
prime-select intel NOT working

### ISSUE THREAD

**Issue by samuelebistoletti** [JackHack96/dell-xps-9570-ubuntu-respin#26]
Hi,
prime-select intel command is not working.
I get this message when I try to launch it: 

Info: selecting the intel profile
Error: the installed packages do not support PRIME

Anyone got this? Any solution?

Thanks

**Comment by JackHack96** [comment]
Please check #3

**Comment by samuelebistoletti** [comment]
It's a different problem. The building process has been completed successfully on kernel module.
I used the post installation script, I have not built the image previously.

**Comment by samuelebistoletti** [comment]
I also noticed that systemctl disable nvidia-fallback command fails with: Failed to disable unit: Unit file nvidia-fallback.service does not exist.

Also I noticed that you removed powertop systemd script, was that generating some kind of problem?

**Comment by JackHack96** [comment]
According to the TLP wiki, it shouldn't be used alongside TLP (powertop is a measuring tool, but its `--auto-tune` setting conflicts with TLP if run at startup)

**Comment by JackHack96** [comment]
Secure Boot is the first thing I disable, because otherwise I cannot use proprietary drivers.
I'm sorry I can't do anything about that...

**Comment by samuelebistoletti** [comment]
It's ok, now I managed to install drivers by disabling secure boot and then re-enabling it. Seems to work.
Thanks

**Comment by cupofjoakim** [comment]
@samuelebistoletti Is everything still working for you? I'm getting this error now and I'm wondering if I'm going to need to disable secure-boot every time i need to swap gfx.

**Comment by samuelebistoletti** [comment]
You need to disable validation before switching profile, every time. I end up with permanently turn off secure boot :(

**Comment by cupofjoakim** [comment]
@samuelebistoletti Yeah, I went that way too. Should be fine for me, but still kind of sucks. Now I just need to figure out why DX11 with wine only works on my intel chip and not the gtx 1050...
