### ISSUE TITLE
Some small tips & tricks

### ISSUE THREAD

**Issue by sjabasti** [JackHack96/dell-xps-9570-ubuntu-respin#28]
Some small tips and tricks, some might be useful for other users:
Don't know if this is the best place for it
Use at your own risk

## Thermal Modes:
On windows there exist a dell power manager to set some hidden bios thermal settings, a similar tool exists for Linux. 
$ sudo apt install smbios-utils
$ sudo smbios-thermal-ctl --set-thermal-mode balanced
smbios supported thermal modes: balanced, cool-bottom, quiet, performance
default = balanced
Arch link of the xps 13: https://wiki.archlinux.org/index.php/Dell_XPS_13_(9370)#Thermal_Modes_.2F_Fan_profiles 
For me it works on the dell xps 9570 as well.

## Undervolting tool:
Use on own risk  
https://github.com/georgewhewell/undervolt

## Fans on while charging but not on battery
Set the mode of tlp to battery while on AC to see if this fixes it
$ sudo tlp bat

## Gnome extension for CPU management
https://extensions.gnome.org/extension/945/cpu-power-manager/

**Comment by JackHack96** [comment]
I didn't know about `smbios-thermal-ctl`. I'll add this thing on the wiki :)
