### ISSUE TITLE
Switching graphic cards does not work 

### ISSUE THREAD

**Issue by bajo** [JackHack96/dell-xps-9570-ubuntu-respin#3]
I used your script to create a new iso and installed it on my xps 9570 today. In the live session I first updated ubiquity to 18.04.3 (see #2 ) and continued installation from there. Everything seems fine. 
The system uses the intel gpu, power usage is quite low (7-8W) as expected. 
However, trying to switch to the nvidia card with `sudo prime-select nvidia` tells me that nvidia profile is already in use, even when I see no proof of that (no high power use, system information shows Intel in the graphics column, etc.)
When I try to switch to Intel with `sudo prime-select intel` it tells me that the currently installed drivers do not support prime.

Any idea what went wrong?

**Comment by JackHack96** [comment]
That's rather strange. I have to fully reboot for switching graphic card, but it works.
Could you please run these commands:
```shell
dpkg --get-selections | egrep "nvidia|bbswitch"
```
and paste the output here?

**Comment by bajo** [comment]
Sure. 
```
dpkg --get-selections | egrep "nvidia|bbswitch"
bbswitch-dkms					install
libnvidia-cfg1-396:amd64			install
libnvidia-common-396				install
libnvidia-compute-390:amd64			deinstall
libnvidia-compute-390:i386			deinstall
libnvidia-compute-396:amd64			install
libnvidia-compute-396:i386			install
libnvidia-decode-396:amd64			install
libnvidia-decode-396:i386			install
libnvidia-encode-396:amd64			install
libnvidia-encode-396:i386			install
libnvidia-fbc1-396:amd64			install
libnvidia-fbc1-396:i386				install
libnvidia-gl-396:amd64				install
libnvidia-gl-396:i386				install
libnvidia-ifr1-396:amd64			install
libnvidia-ifr1-396:i386				install
nvidia-compute-utils-396			install
nvidia-dkms-396					install
nvidia-driver-396				install
nvidia-kernel-common-396			install
nvidia-kernel-source-396			install
nvidia-prime					install
nvidia-settings					install
nvidia-utils-396				install
xserver-xorg-video-nvidia-396			install
```

**Comment by bajo** [comment]
It seems the nvidia kernel module is not built. During the original installation the installer even crashed somewhere at the point of either `update-initramfs` or `update-grub`. Thus I had to chroot into /target and do a manual `update-grub` to get a bootable system.
When I now try to build the nvidia module with dkms I receive the following errors.

```
Building module:
cleaning build area...
unset ARCH; env NV_VERBOSE=1 'make' -j12 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=4.18.0-041800rc3-generic IGNORE_XEN_PRESENCE=1 IGNORE_CC_MISMATCH=1 SYSSRC=/lib/modules/4.18.0-041800rc3-generic/build LD=/usr/bin/ld.bfd modules.......(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-4.18.0-041800rc3-generic is not supported
Error! Bad return status for module build on kernel: 4.18.0-041800rc3-generic (x86_64)
Consult /var/lib/dkms/nvidia/396.24.02/build/make.log for more information.
```

**Comment by JackHack96** [comment]
I'm going to update an ISO with ubiquity patches, so I think the nvidia module should build just fine.

**Comment by bajo** [comment]
I did end up rebuilding the iso with the v4.15 kernel. Afterwards installation worked with the above mentioned `chroot` method. But the important thing is that the Nvidia kernel module is now built and switching from Intel to Nvidia gpu works just fine. 
Thank you for the quick help.
