### ISSUE TITLE
respin breaks encrypted boot

### ISSUE THREAD

**Issue by johnruttenberg** [JackHack96/dell-xps-9570-ubuntu-respin#30]
I have full disk encryption.  I had everything working from about the beginning of August but thought I'd rerun respin to get new work.
Now I can't boot.  Instead of showing the screen with the prompt for the disk password, it shows a new Ubuntu screen and then ends up with an prompt to unlock the disk.  But entering my password into that prompt doesn't work.

I tried to boot into an older kernel but same problem.

Help!

**Comment by johnruttenberg** [comment]
I did manage to boot after typing the disk password VERY carefully to the text prompt with no feedback.  Leaving the bug open in case someone knows how to get the disk password screen back.

**Comment by JackHack96** [comment]
I'm sorry, I can't help with this problem :disappointed:

**Comment by appollo101** [comment]
did you try the new bios 1.4.1 released on Sept 21?

**Comment by uocxp** [comment]
i had the same problem, but after changing the value of GRUB_OPTIONS to "quiet splash acpi_rev_override=1" i got the old screen with the prompt

**Comment by Dodenis** [comment]
I confirm the problem.
To solve it, you have to put the "splash" option in Grub just after the "quiet" option.

**Comment by johnruttenberg** [comment]
Please can you provide complete instructions? What file to edit? How to
process it after the change is made? I tried to do this but didn’t have
success. I don’t think I really know what I am doing. Thanks for the help.

**Comment by Dodenis** [comment]
Here is what I did : 

Edit the file /etc/default/grub with sudo
`sudo vim /etc/default/grub`
Add "splash" in the "GRUB_CMDLINE_LINUX_DEFAULT" variable juste after "quiet"
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash ..."`
Save and quit file.
Then update grub with command : 
`sudo update-grub`

That all.

**Comment by johnruttenberg** [comment]
It worked!  Thank you.
