### ISSUE TITLE
No install option when using already respun ISO

### ISSUE THREAD

**Issue by soudk** [JackHack96/dell-xps-9570-ubuntu-respin#32]
Hi JackHack96, 

First of all, thank you for doing this and uploading your stuff. It's awesome. 

I'm trying to use your already respun ISO to install it in dual boot with windows 10. However, I can boot into live mode from a USB but the installer is not present. Any idea what could be going wrong? Could you maybe post some steps what exactly you did to install? Did you have to change your RAID settings, etc...?

**Comment by keatonzx** [comment]
I am having this issue too, I tried changing my SATA operations but that did not work

**Comment by keatonzx** [comment]
It also seems to be the case when spinning your own

**Comment by keatonzx** [comment]
Also tried spinning my own and booting in legacy mode

**Comment by seboudry** [comment]
Hi!
Also try with bundle ISO and spinning (at commit `d9376ba`) myself and I have same issue.
I'll try to isolate when this installer icon disappear because I've already use this respin successfully by the time.

**Comment by keatonzx** [comment]
I was able to install Ubuntu 18.04 and spin it after the fresh install, works great now.

**Comment by seboudry** [comment]
Moreover it's this line that have impact:
https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/blob/master/update-packages.sh#L4
If we don't need to add bionic-proposed ppa, I advise to remove this line.

**Comment by JackHack96** [comment]
Thank you @seboudry for taking your time testing the ISO.
I deleted `gpuoff.service` because Ubuntu developers fixed the issue regarding power usage, and the related packages are in the proposed repo.

**Comment by soudk** [comment]
Hmm, now I'm having the issue of a black screen when trying to boot from the USB... Could someone please help me with the MBR vs GPT partitioning options and legacy vs UEFI ( with secure boot off) stuff?
