### ISSUE TITLE
Missing packages on xps-tweaks.sh

### ISSUE THREAD

**Issue by leoheck** [JackHack96/dell-xps-9570-ubuntu-respin#33]
There are no `tlp-rdw`, `powertop` and `thermald` on [ppa:linrunner/tlp](https://launchpad.net/~linrunner/+archive/ubuntu/tlp) 

![image](https://user-images.githubusercontent.com/1277920/46051821-9b5d7c00-c111-11e8-88cd-f432c43d3e25.png)

**Comment by JackHack96** [comment]
I know, in fact they all get installed from the universe repository. But adding the PPA is for getting sure users will get eventual updates.
