### ISSUE TITLE
Loose cursor after suspend

### ISSUE THREAD

**Issue by kingjr** [JackHack96/dell-xps-9570-ubuntu-respin#34]
Hi,

After I suspend, I can't control (and sometimes see) the mouse cursor. Fortunately, because it's a touchscreen, I can still do stuff. 

Any idea on how to fix this?

Thanks!

**Comment by JackHack96** [comment]
Uhm, It's a rather generic description, I don't know how to solve it.

A quick Google search revealed that it seems a common bug ([https://bugs.launchpad.net/xserver-xorg-video-intel/+bug/1568604](https://bugs.launchpad.net/xserver-xorg-video-intel/+bug/1568604)).
Try the suggested method ([https://ubuntuforums.org/showthread.php?t=2335005](https://ubuntuforums.org/showthread.php?t=2335005))

**Comment by jhe-** [comment]
I had a similar problem where the mouse was being powered off by tlp. I found [this solution](https://askubuntu.com/a/1026527/849733) on StackExchange, which gets rid of the freezes for my mouse. Basically it does the same as manually running powertop, tabbing to the "Tunables" page, and disabling power-saving for the mouse (and every other "HID" device) by setting it from "Good" to "Bad". Except that it needs to run every startup, as I haven't yet found a way to prevent tlp from resetting it yet.

My full `powertop.service` file looks like this:

```
[Unit]
Description=Powertop tunings

[Service]
Type=oneshot
ExecStart=/bin/bash -c "HIDDEVICES=$(ls /sys/bus/usb/drivers/usbhid | grep -oE '^[0-9]+-[0-9\.]+' | sort -u); \
for i in $HIDDEVICES; do \
  echo -n 'Enabling ' | cat - /sys/bus/usb/devices/$i/product; \
  echo 'on' > /sys/bus/usb/devices/$i/power/control; \
done; \
"

RemainAfterExit=true

[Install]
WantedBy=multi-user.target
```
