### ISSUE TITLE
4k@60Hz via HDMI

### ISSUE THREAD

**Issue by rdzak** [JackHack96/dell-xps-9570-ubuntu-respin#36]
First of all thanks for this amazing work!

Now the question: is there a way to enable 4k monitor refresh rate to be higher than 30Hz via HDMI? 
It works in Windows so not a hardware issue with cable or screen. I have tried setting it up while using Intel or Nvidia but no luck.

Thank you!

**Comment by JackHack96** [comment]
Have you tried using xrandr?

**Comment by timkgh** [comment]
@rdzak does your monitor support HDMI 2.0? Sometimes there may be multiple HDMI ports on the monitor but only one of them is 2.0 Also, use a quality HDMI cable.
