### ISSUE TITLE
Multi-monitor setup scaling issues

### ISSUE THREAD

**Issue by DCdeBrabander** [JackHack96/dell-xps-9570-ubuntu-respin#38]
Using this ISO I cannot get multi-display to work normally..

I get all kinds of issues like:
 - weird scaling issues, where the primary (builtin) display is 4k with 200% scaling but the 2nd 1920x1080 display would scale (locked) 200% as well (which is ridiculous). 
- if using scaling config 'hack', tweak tools (even enable Wayland), w/e, 
   you get other weird issues such as: 
  - create weird blurry-ness in seperate parts of the OS or different programs. 
  - driver/nvidia issues

I'm probably forgetting 90% of what I've tried but I'm mostly curious who else encounters these problems on this system. This is holding me back from using this 9570 in Linux primarily and professionally and basically stuck with the bloated Windows (which is upgraded to pro at least)

**Comment by JackHack96** [comment]
Scaling problems are, unfortunately, a plague in Linux systems. I have the FHD model for that reason, because I don't have to scale anything.

**Comment by timkgh** [comment]
I found that the built-in 4K screen does a pretty good job at upscaling a lower resolution. Configure the external monitor first to look good to you, then lower the *resolution* of the internal display until it looks decent. You can automate the process of changing the settings between laptop mode and external monitor with https://github.com/jceb/screenconfig
I also found that I get better results when I only scale the fonts via `gnome-tweaks` (fractional scaling for fonts works). I prefer to keep the display scaling at 100% and just set font scaling at 1.8-2.0, this way icons and the taskbar don't waste a lot of screen space. Most widgets and apps will adjust accordingly. There will be odd ones that may need individual tweaking.
I have not had good luck messing with `xrandr` scaling, it results in blurry fonts, I can get the same or better results by running external monitors at lower resolutions and letting them do the upscaling and increasing the sharpness setting on the monitor (sometimes called "super" resolution). But I like the font scaling approach much better, it results in crisp looking text.
It can be made to work fairly well, but it takes a bit of work and sometimes you may have to keep some scripts handy and run them when you switch between setup :(

**Comment by alex-pub** [comment]
I've had a moderate success with doubling the frame buffer and then scaling down the resolution of the external screen with:

```
xrandr --fb 7680x2160 &&
xrandr --output eDP-1 --mode 3840x2160 --rate 60 --primary &&
xrandr --output DP-3 --mode 1920x1080 --scale-from 3840x2160 --panning 3840x2160+3840+0 --right-of eDP-1 &&
gsettings set org.gnome.desktop.interface scaling-factor 2
```

The scaling down part does result in a slightly _blurry_ image (consistent) on the external display, but it's really not that bad and it's definitely useful, YMMV. This will, of course, set the external screen to the right of the laptop screen, you'll need to change the frame buffer size and `--panning` settings for other geometries.

**Comment by JackHack96** [comment]
With 3.32 GNOME release, is seems fractional scaling is working ok (though I can't properly test it given that I don't have any >1080p monitor)

**Comment by jogelin** [comment]
@JackHack96 does it mean we have to upgrade to 18.10 ? ;)

**Comment by hetsch** [comment]
I think the 3.32 does not even make it into 19.04. Ubuntu Devs stick to 3.30 for 19.04. https://discourse.ubuntu.com/t/staying-on-gnome-software-3-30-for-disco/10192

**Comment by JackHack96** [comment]
@hetsch Uhm, not sure about it. I have to check in the daily lives, they should be using 3.32 (it's possible though that they chose to use earlier version of some software like GNOME software, for whatever reason).
@jogelin 18.10 is not enough, if 19.04 will ship with 3.32, then we should upgrade to it if we want fractional scaling.
Maybe a live test with a daily iso should give you an overview if it's worth upgrading.

**Comment by DCdeBrabander** [comment]
@JackHack96  You adding the `wontfix` tag after saying "Scaling problems are, unfortunately, a plague in Linux systems." basically made me checking (and in the end going) for solutions like: https://system76.com/pop which I can recommend. 

Having 4k monitors is a reality nowadays, laptop or external, and I was very disappointed to learn that many distro's have issues with this out-of-the-box.  

I was hoping we could include a fix/script/deamon/..w/e ourselves in this respin until Gnome (or wayland for that matter) finally get some relevant and decent updates released.

What is your perspective on this whole matter is basically what I'm trying to ask :D.

**Comment by JackHack96** [comment]
I'm aware of PopOS, which is basically Ubuntu with many other enhancements.
A script or something similar is not sufficient, the work required is at code level. Fortunately, Ubuntu devs are still working to address this issue, and with 19.04 the results are promising (though not perfect).

Personally, I think the only way of adding decent 4k support for 18.04 is building GNOME 3.32 and manually installing it, but this will result in a "Frankenstein OS" of unmaintained mess...

**Comment by timkgh** [comment]
You can experiment with it and enable fractional scaling in Ubuntu 18.04 if you switch to Wayland:
https://www.valhalla.fr/2018/07/14/hidpi-on-gnome-desktop/
I tried it, didn't look good, looked a bit blurry. Maybe they have a better implementation in Gnome 3.32 than in 3.28

See my comment above what worked well for me (X with font scaling which will also scale most UI components, try it):
https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/issues/38#issuecomment-436338438
