### ISSUE TITLE
Unable to respin

### ISSUE THREAD

**Issue by luposlip** [JackHack96/dell-xps-9570-ubuntu-respin#4]
Hi there,

Thanks for the good repo!

I can't finish the respin run:
```
➜  dell-xps-9570-ubuntu-respin git:(master) ✗ sudo ./build.sh ubuntu-18.04-desktop-amd64.iso
Extracting ISO ...
Parallel unsquashfs: Using 4 processors
139912 inodes (156845 blocks) to write

[=========================================================\] 156845/156845 100%

created 112482 files
created 16964 directories
created 27397 symlinks
created 7 devices
created 0 fifos
Extracting isorespin files ...
Processing bootloader/bootmanager ...
Fetching mainline kernel packages ...
Installing mainline kernel packages ...
Adding repositories ...
WARNING:root:system-image-cli failed, using defaults: [Errno 13] Permission denied: '/dev/null'
WARNING:root:system-image-cli failed, using defaults: [Errno 13] Permission denied: '/dev/null'
WARNING:root:system-image-cli failed, using defaults: [Errno 13] Permission denied: '/dev/null'
Cannot add PPA: 'ppa:~graphics-drivers/ubuntu/ppa'.
ERROR: '~graphics-drivers' user or team does not exist.
./isorespin.sh: Adding repository 'ppa:graphics-drivers/ppa' failed.
```

Respinning on a Ubuntu 18.04 (on a Dell XPS 9360).

Any idea?

Best,
Henrik

**Comment by JackHack96** [comment]
Oh my gosh, this is the same error that happens to me when I try to use the isorespin script on my desktop computer.
Unfortunately, this isn't my fault, it's something in the `isorespin.sh` script which is not working, however I still didn't understand what's causing the error.
I'm not sure it's something about Ubuntu 18.04 also, because on my XPS I can respin it...

**Comment by luposlip** [comment]
Hmm, OK.
Could you put a respun ISO out somewhere for me to test?

**Comment by JackHack96** [comment]
Ok, tomorrow I'll upload an ISO in my Google Drive, because GitHub doesn't allow me to send files >2GB

**Comment by JackHack96** [comment]
I've builded the ISO, with my crappy 7mbit connection I can't upload it from home, I'll do that at my university :smile:

**Comment by JackHack96** [comment]
BTW, I've managed to build and upload the ISO using one of the University servers, you can download it from the link in the README :wink:

**Comment by luposlip** [comment]
Thanks a bunch! Will try it in 4-6 hours! :)

**Comment by luposlip** [comment]
Tried it 2 times now - the installer crashes before finishing.

The standard ISO finishes installation on my machine, and shows login prompt, but doesn't finish loading the desktop after logging in (shows only the mouse pointer on the standard colored background, no icons or anything - plus it freezes). I can re-show the login prompt by pressing ALT+F1.

Well, think I might give up for now, and just install Ubuntu in a Virtual Box :(

Thanks anyhow.

**Comment by luposlip** [comment]
Just for your (and others) info: I tried to install Kubuntu 18.04 - it worked the first time, without any issues at all. After first boot, it detected the need for proprietary drivers for the nvidia gfx adapter. I just accepted the installation, and all is good.

The fingerprint reader doesn't work of course. Let me know if you figure out how to! :)

**Comment by luposlip** [comment]
Updated: Really happy about the Ubuntu Budgie - it works like a charm (except the Goodix fingerprint sensor):
https://ubuntubudgie.org/

**Comment by gravyplaya** [comment]
I am having the same issue. has it been fixed?

**Comment by JackHack96** [comment]
It's an error of the respin script (which I didn't write, and it's too big for debugging).
I have that issue on some machines too, that's why I created the already respun ISO
