### ISSUE TITLE
msttcorefonts

### ISSUE THREAD

**Issue by Kurgol** [JackHack96/dell-xps-9570-ubuntu-respin#41]
I don't know why your script is installing msttcorefonts or why they would be required to make the drivers for a Dell work, but whatever mirror you used for the files is not working so every time I run install script, it spends 10 mins trying to download them, bombs out and they gives me an error.

**Comment by Kurgol** [comment]
I'm also particularly worried that when I inspect https://raw.githubusercontent.com/JackHack96/dell-xps-9570-ubuntu-respin/master/xps-tweaks.sh manually, I don't see anything to do with installing fonts, so how the hell is it triggering?

**Comment by Kurgol** [comment]
aha! It's this line:

```
# Install codecs
apt -y install ubuntu-restricted-extras va-driver-all vainfo libva2 gstreamer1.0-libav gstreamer1.0-vaapi
```

can you confirm which others on the "codecs" line are unnecessary for a working system?

**Comment by Kurgol** [comment]
so can I omit the whole line, if not please can you confirm which of those "codecs" are required to get the device working?

I want drivers, I don't want codecs.

**Comment by JackHack96** [comment]
Yes, you can simply delete the whole line without problems :)

**Comment by Kurgol** [comment]
awesome cheers!
