### ISSUE TITLE
Ubuntu 18.10

### ISSUE THREAD

**Issue by leoheck** [JackHack96/dell-xps-9570-ubuntu-respin#42]
Hi @JackHack96!

Did you try the new Ubuntu 18.10? I have some issues running it. It is actually useless right now. If you give a try just let me know.

**Comment by JackHack96** [comment]
No I didn't try it.
You can however try to boot it with the special GRUB options of the respin. Go the wiki to see them

**Comment by leoheck** [comment]
I was able to fix everything, it is working fine. I will come back later with the info.

**Comment by leoheck** [comment]
I put some info here https://www.reddit.com/r/Dell/comments/9puckt/ubuntu_1810_on_dell_xps_15_9570/

**Comment by JackHack96** [comment]
Oh I see.
I'm going to put a link in the README file :)

**Comment by Eelviny** [comment]
I know this is closed but it's also about Ubuntu 18.10:

Just thought I'd let you know that I was able to run the xps_tweaks.sh script on my 18.10 setup and my laptop works really well - much better than it was before. Maybe it would be worth adding 18.10 to the allowed distros in the script?

Things that I'm having issues with:
- Upon resuming from suspend, oftentimes the Bluetooth adapter is not found, requiring a reboot
- Upon resuming from suspend, sometimes NetworkManager loses control of the WiFi adapter, but it's still functional
- The splash screen on startup doesn't show, only text
