### ISSUE TITLE
Fan speeds doesn't go above 3200 rpm

### ISSUE THREAD

**Issue by Cznielsen** [JackHack96/dell-xps-9570-ubuntu-respin#43]
As stated in the title, my fan speeds doesn't go above 3200 rpm (when connected to AC at least) even though the laptop is reaching 97 degrees celcius. Is there a setting I can change anywhere or would I need to utilise i8kutils? I've tried it in the past but it doesn't really work that well for me.

Thanks

**Comment by JackHack96** [comment]
Please check the wiki page [https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/wiki/Some-useful-tips-and-tricks](https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/wiki/Some-useful-tips-and-tricks)

**Comment by timkgh** [comment]
How do you monitor the fans on the 9570? `sensors-detect` doesn't detect any fans. Any recommended GUIs for Ubuntu?

**Comment by Cznielsen** [comment]
> How do you monitor the fans on the 9570? `sensors-detect` doesn't detect any fans. Any recommended GUIs for Ubuntu?

I use Psensor to add the fan speeds and temperatures to the top bar (Also cpu usage and amount of free ram left).

**Comment by timkgh** [comment]
No, that's the problem, I don't know what kernel module is needed to monitor the fans, `coretemp` is not enough. I'm on kernel 4.19 as I was trying to resolve the suspend/hibernate problems. `sensors` hangs trying to read a temp from ath10k (and there's a related `dmesg` error: `failed to synchronize thermal read`) but then it goes thru and shows the CPU temps, but no fan speeds. Temps seems well behaved and fans don't run all the time, they come on once in a while, seems like they are behaving but I'd like to keep an eye on them at least initially.

**Comment by JackHack96** [comment]
I still didn't try to read sensors from my XPS, but you may need to edit the `/etc/sensors3.conf` like I did on my desktop PC, as it seems that `lm-sensors` is no longer maintained :pensive:

**Comment by JackHack96** [comment]
I'll integrate this in the respin and in the tweak script

**Comment by timkgh** [comment]
Also found this page from the amazing Arch Linux wiki:
https://wiki.archlinux.org/index.php/Dell_XPS_15_9560
`modprobe dell-smm-hwmon ignore_dmi=1` works too, but it doesn't work with any options, so not sure which all options we need.
