### ISSUE TITLE
[Question] isorespin.sh

### ISSUE THREAD

**Issue by markbref** [JackHack96/dell-xps-9570-ubuntu-respin#5]
Hi, thanks for this. Besides some weird pixels at the bottom of the screen at login, this iso is working as expected :)

I have a question though, do you know what that is in the isorespin.sh file at the bottom after `exit 0` ?
`UEsDBBQAAAAIABZ2i0yWx/2OPAUAAOQMAAATABwAbGludXhpdW0tYm9vdHNjcmlwdFVUCQADrJPN...`

**Comment by JackHack96** [comment]
Those weird pixels at the bottom of the login screen are "normal", because of the experimental options I activated.
As for the line at the bottom of isorespin.sh I don't know, because the script is not mine

**Comment by markbref** [comment]
Ah ok - the pixels is relay also not a problem. 

Regarding the bottom of isorespin.sh, I was just hoping you might know what that was about.
I tried to find a repo for the isorespin.sh, but the only one I could find was [this](https://gist.github.com/rgooler/3ceede23606e4624d5c57ea8cce5dec7) but that has nothing after the `exit 0`

My best guess is that it is some binary payload - but for what.

Anyways, thanks for clarifying! :)

**Comment by JackHack96** [comment]
The original isorespin.sh was published [here](http://linuxiumcomau.blogspot.com/2017/06/customizing-ubuntu-isos-documentation.html).
I picked that one for respinning ISOs. It could be a payload, but I dont' know for what. Unfortunately, I can't help, I'm not an expert of these sort of things.

**Comment by mlopezantequera** [comment]
I asked here about the binary part of isorespin.sh: http://linuxiumcomau.blogspot.com/2017/06/customizing-ubuntu-isos-documentation.html

```
    Manu26 July 2018 at 20:21
    Hi!
    I'm wondering: what is the binary taking up most of the filesize?

    Linuxium26 July 2018 at 20:42
    Can you be more specific and specify the name of the binary and its size?

    Manu26 July 2018 at 20:48
    Hi, sorry to be so vague.
    I'm referring to the large number of lines following the last script line. (After line 4067)

    Linuxium26 July 2018 at 21:17
    They are the minimum set of bootloader files used by the script to support booting on Atom and       Apollo devices.
```

**Comment by JackHack96** [comment]
Good to know it's safe!
