### ISSUE TITLE
prime-select intel high idle watts, use bbswitch to turn card off

### ISSUE THREAD

**Issue by mdevrees** [JackHack96/dell-xps-9570-ubuntu-respin#50]
Hi to all reading this,

I downloaded your already respun ISO and installed everything. Switched the `prime-select query` to `intel` (it was displaying `nvidia`) but the idle watt usage in Powertop was still high (around ~12W-15W ish). I saw the installationg of bbswitch coming along in the xps-tweaks.sh script. 

By default bbswitch is not initialized at boot, but you can do so via `sudo modprobe bbswitch` and then it will create a file called `/proc/acpi/bbswitch` with value `0000:01:00.0 ON`. Since the prime-select is now `intel`, it should not use the nvidia driver and you should be able to turn it off with
```
sudo tee /proc/acpi/bbswitch <<<OFF
```

You can also create a modprobe file (sudo touch /etc/modprobe.d/bbswitch.conf) and add 
```
options bbswitch load_state=0 unload_state=1
```
which will turn it off on load (the loading of the module) and turn it on on unload (the unloading of the module at computer off for example).

For some reason I cannot get bbswitch to load on computer start, but I don't mind using `sudo modprobe bbswitch` on every boot.

My machine has an i7 8550H with 16GB of ram and the 1080p screen, non-touch.
On 50% brightness, idle watts are now around 7W

**Comment by JackHack96** [comment]
Uhm that's strange, normally `bbswitch` should not be needed for powering off the nvidia card, it should be automatic with prime-select.

**Comment by mdevrees** [comment]
Yes it is. While prime-select is set to Intel, it still leaves the card 'on'
I googled around a bit and found [this comment](https://github.com/stockmind/dell-xps-9560-ubuntu-respin/issues/8#issuecomment-389292575). I created the systemctl startup script as mentioned and now without bbswitch it works fine. Not sure if others experience the same issue.
