### ISSUE TITLE
Update ready to use ISO

### ISSUE THREAD

**Issue by vikrambombhi** [JackHack96/dell-xps-9570-ubuntu-respin#51]
## Issue
I dont think the downloadable [ready yo use ISO](https://drive.google.com/open?id=1ciXfa3FGTlujaPJCsv54yFfmTuVxk_vd) is up to date (the details on link show it was last updated Sep 27). Can we replace it with a newer version? Also we should state in the README.md when google drive iso was last updated.

### Possible long-term solutions
1. Automating the iso build with CI and having it upload to the drive link would be ideal.
1. Using tagged 'releases'. Github will handle releases for us, this is what the parent project of this fork is doing, you can download their releases [here](https://github.com/stockmind/dell-xps-9560-ubuntu-respin/releases)

**Comment by JackHack96** [comment]
That would be ideal, but I don't know how to automate ISO build and uploading to my Google Drive (and updating the link in the README). Could you help me with that?

**Comment by vikrambombhi** [comment]
I looked into it. Unfortunately, I don't think we can use Circle CI or Travis CI because they don't support git lfs on public repos. We can use Jenkins but we would need to set up a Jenkins server somewhere. I tried to setup the Jenkins server on a spare raspberry pi I have but unfortunately, the build script does not run on arm.

**Comment by vikrambombhi** [comment]
Hey @JackHack96 I got the build process working using Jenkins. It triggers whenever master on my [fork](https://github.com/vikrambombhi/dell-xps-9570-ubuntu-respin) gets updated. It would be pretty trivial to have it upload the image to google drive when it's done. Let me know if you want to set it up using ur fork instead.

**Comment by JackHack96** [comment]
Can I add you as a collaborator? I would like to see it set up on the this repo :smile:

**Comment by vikrambombhi** [comment]
For sure! Add me and ill set it up. PS also setup a
