### ISSUE TITLE
Black screen after ubuntu booting screen

### ISSUE THREAD

**Issue by jogelin** [JackHack96/dell-xps-9570-ubuntu-respin#56]
Hello !

I'm trying your respin image but after installation, ubuntu seems to boot correctly then I just have a black screen and fans are just going up then down..etc...

I had the same issue when I tried to boot on the live ubuntu...

I don't really know what to do now :D 

When I am on the black screen state, I can open virtual console `crtl + alt + f5` then I see repeating errors (I had to make a video and make a printscreen :) ): [Image](https://imgur.com/a/DdNkxkq)

**Comment by jogelin** [comment]
Finally I setup again and it works.....

**Comment by Grybouilli** [comment]
Hey, I'm encountering the same issue, what exactly did you do to fix it ?

**Comment by jogelin** [comment]
@Grybouilli just make a clean install again...without thinking about a partition for windows for the moment...now it is working perfectly since 1 month !

**Comment by Grybouilli** [comment]
That's what I did, everything seems in order! I may have the fans running all the time thought, I read it is a common problem. Did you use the tweaks script ?

**Comment by jogelin** [comment]
Yes I am using the tweak scripts. 

In my case I am only using the `intel` graphic card (not `nvidia`) and I am also using the `cpu power manager gnome extension` ([https://extensions.gnome.org/extension/945/cpu-power-manager/](https://extensions.gnome.org/extension/945/cpu-power-manager/))

I think for the moment there a bug with the nvidia selection related to the fan...not sure I remember something about that

**Comment by Grybouilli** [comment]
I'll do that then, thanks for the replies!

**Comment by Grybouilli** [comment]
Just switched to intel and I never had such a quiet computer ! 
Also will try the cpu power manager gnome extension that you linked, thanks for the advices!
