### ISSUE TITLE
Fan spinning periodically

### ISSUE THREAD

**Issue by ai2010** [JackHack96/dell-xps-9570-ubuntu-respin#57]
Hi,

Thanks for the scripts and I still have a problems with fans. Periodically the cpu cores go a bit above 80 C so the fans start spinning at 5000 rpm . It happens every 5-10 mins... not sure why.. I also tried to run systemctl disable nvidia-fallback' but I got 'Failed to disable unit: Unit file nvidia-fallback.service does not exist.'   How did you set the fans? Any help appreciated.

**Comment by JackHack96** [comment]
This indicates that the nvidia driver was not correctly installed, maybe something went wrong during installation.

I suggest you to reinstall the nvidia driver with the following commands:
```shell
sudo apt autoremove --purge $(dpkg --get-selections | grep nvidia | awk '{print $1}')
sudo apt update
sudo apt install nvidia-driver-415
```

**Comment by ai2010** [comment]
Thanks for your reply. I just did what you suggest... same error

**Comment by jungla88** [comment]
Nvidia Driver should not be the problem. I experienced the same and I have nvidia-driver 415 on.
I think the ISO is optimezed for 1050Ti, while others XPS15 may have 1050

**Comment by ai2010** [comment]
I am using Wayland if that matters

**Comment by ai2010** [comment]
yes I did:

# dmidecode 3.1
Getting SMBIOS data from sysfs.
SMBIOS 3.1.1 present.

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
	Vendor: Dell Inc.
	Version: 1.6.0
	Release Date: 11/02/2018
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 32 MB
	Characteristics:
		PCI is supported
		PNP is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		EDD is supported
		Japanese floppy for NEC 9800 1.2 MB is supported (int 13h)
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		Print screen service is supported (int 5h)
		8042 keyboard services are supported (int 9h)
		Serial services are supported (int 14h)
		Printer services are supported (int 17h)
		ACPI is supported
		USB legacy is supported
		Smart battery is supported
		BIOS boot specification is supported
		Function key-initiated network boot is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 1.6

**Comment by JackHack96** [comment]
> I am using Wayland if that matters
> Also I have noticed that switching on i8kmon from terminal it will put the fans down for 1-2min then again... I also put i8kmon on startup application but apparently doesn't work.. I already installed dell-bios-fan-control (from [TomFreudenberg/dell-bios-fan-control](https://github.com/TomFreudenberg/dell-bios-fan-control))

Ahh this is a game-changer!
I don't know which graphic card the wayland session uses, but as far as I know the nvidia driver is not loaded. If nouveau is in use then it's normal to hear the fans spinning.

**Comment by jungla88** [comment]
So dell-bios-fan-control is not working for you?

**Comment by JackHack96** [comment]
I don't use that software, I use Xorg and the fan are off most of the time (because I use the Intel card)

**Comment by ai2010** [comment]
> So dell-bios-fan-control is not working for you?

I suspect it doesn't because I tried already 3 times

**Comment by jungla88** [comment]
Run 

> sudo dell-fan-bios-control 0

 and then try 

> i8kfan 0 0

This should permanently disable the fans. Just to check if bios has control over the system

**Comment by ai2010** [comment]
How can I check if the bios has control?

**Comment by ai2010** [comment]
andrea@andrea:~$ cd dell-bios-fan-control/
andrea@andrea:~/dell-bios-fan-control$ sudo ./dell-bios-fan-control 0
[sudo] Mot de passe de andrea : 
BIOS CONTROL DISABLED
andrea@andrea:~/dell-bios-fan-control$ i8kfan 0 0
1 1
andrea@andrea:~/dell-bios-fan-control$ sensors
pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:        +65.0°C  

acpitz-virtual-0
Adapter: Virtual device
temp1:        +25.0°C  (crit = +107.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +68.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +67.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +64.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +67.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +68.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +65.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +65.0°C  (high = +100.0°C, crit = +100.0°C)

dell_smm-virtual-0
Adapter: Virtual device
fan1:           0 RPM
fan2:           0 RPM

andrea@andrea:~/dell-bios-fan-control$ sensors
pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:        +65.0°C  

acpitz-virtual-0
Adapter: Virtual device
temp1:        +25.0°C  (crit = +107.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +73.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +65.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +73.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +65.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +63.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +61.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +63.0°C  (high = +100.0°C, crit = +100.0°C)

dell_smm-virtual-0
Adapter: Virtual device
fan1:        5106 RPM
fan2:        5093 RPM

andrea@andrea:~/dell-bios-fan-control$ sensors
pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:        +65.0°C  

acpitz-virtual-0
Adapter: Virtual device
temp1:        +25.0°C  (crit = +107.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +78.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +67.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +65.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +78.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +63.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +65.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +62.0°C  (high = +100.0°C, crit = +100.0°C)

dell_smm-virtual-0
Adapter: Virtual device
fan1:        5100 RPM
fan2:        5080 RPM

andrea@andrea:~/dell-bios-fan-control$ sensors
pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:        +64.0°C  

acpitz-virtual-0
Adapter: Virtual device
temp1:        +25.0°C  (crit = +107.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +74.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +74.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +63.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +63.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +62.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +60.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +61.0°C  (high = +100.0°C, crit = +100.0°C)

dell_smm-virtual-0
Adapter: Virtual device
fan1:        5093 RPM
fan2:        5080 RPM
