### ISSUE TITLE
New xps 15 intel i9 1050ti gtx, unable to install

### ISSUE THREAD

**Issue by McCoyBecker** [JackHack96/dell-xps-9570-ubuntu-respin#62]
I just received an xps 15 and I've been trying to install your respin. No matter what I do, I can't get it to boot up, even after acpi= off, nomodeset, etc. I updated the BIOS to 1.6 and got the latest Nvidia driver on the windows side. I'm still have issues with NVMR - it constantly tries to probe the GPU and fails on a loop. Any suggestions?

**Comment by Grybouilli** [comment]
I've personnaly used the official iso, made a clean install and then used the tweaks script provided in the repo, it works well so far !

**Comment by JackHack96** [comment]
I think it's due to preloaded nVidia drivers, I'll try to build the ISO without them

**Comment by andreabat** [comment]
Hi, got my xps in Decemeber, after many trials I managed by booting in rescue mode.
In the console I purged all nvidia drivers
`sudo apt-get purge nvidia*`

It automatically got noveau driver configured, after reboot it loaded up gnome.

I completed all updates,  and then installed nvidia driver from the "software and updates" "additional drivers". Works like a charm so far.
