### ISSUE TITLE
Does this respin work for 9560?

### ISSUE THREAD

**Issue by mike1808** [JackHack96/dell-xps-9570-ubuntu-respin#68]
I'm using stockmind/dell-xps-9560-ubuntu-respin with Ubuntu 17.10 and want to upgrade to 18.04. However the original repo only supports 17.10. Will this repo work for 9560? Did anyone try? As I know the only difference between 9560 and 9570 is CPU.

**Comment by nithjino** [comment]
No guarantee that it'll work but you can try. I use the script to respin kubuntu 18.10 and it works just fine for me. I have the 9570

**Comment by JackHack96** [comment]
I have two friends with a 9560 and I helped them setting up Ubuntu, it worked everything. So you shouldn't have issues

**Comment by mike1808** [comment]
@JackHack96 did you try Ubuntu 18.04 or the latest version? Also, I heard that there are issues with bluetooth with Ubuntu 18 and it doesn't work after suspend. Is that true with this respin?

**Comment by JackHack96** [comment]
I installed them the 18.04 version. Well neither I nor them use Bluetooth, so I don't know if it has issues.

**Comment by vikrambombhi** [comment]
@mike1808 I have the Bluetooth issue you described, sometimes it happens with my wifi too. Honestly, it occurs so rarely that it doesn't bother me and a quick reboot always fixes the issue.
