### ISSUE TITLE
Does not work for me..

### ISSUE THREAD

**Issue by pabb85** [JackHack96/dell-xps-9570-ubuntu-respin#7]
Hi Jack,

I've tried using your respin a couple of times now but it leaves me in the same position. I had initially installed 18.04 manually and got it working with a few tweaks but the latest updates on the ubuntu repo's break the build - instability especially on suspend.

It seems the only current way to get it working would be to hold back some packages/updates, after figuring out which was causing the issues.  

Any advice other than wait for this issues to be fixed in the ubuntu repos?

Thank you,
P.

-

**Comment by JackHack96** [comment]
The script that builds the ISO automatically updates all packages, that's the reason.

Do you know which packages are causing issues?

**Comment by pabb85** [comment]
Ahh yes - figured this would be the issue.  Thank you

I'm not entirely sure which packages are causing the issue but suspect it's the problem that a few people have mentioned on various forums recently about bbswitch not being able to properly handle the nvidia graphics any more - breaking the suspend functionality.  I'm half tempted to just wait out a fix rather than start pinning back package versions, though...

**Comment by JackHack96** [comment]
I have an updated system, and I have the proposed repository active, and I currently don't have problems with suspend and resume...

**Comment by pabb85** [comment]
Nice!  I did not try this - I don't usually go for the bleeding edge but if this works, I'll be doing it tonight - thank you Jack!

P.

**Comment by JackHack96** [comment]
Here are my specs:
![https://i.imgur.com/w54sI29.png](https://i.imgur.com/w54sI29.png)

**Comment by pabb85** [comment]
Confident that mine will work then, given the proposed repo is enabled and updated against tonight.... Fingers crossed!

**Comment by JackHack96** [comment]
Does it work now?

**Comment by pabb85** [comment]
It didn't unfortunately but I did figure out a fix :)

Forcing S3 mode sleep in the BIOS does the trick and resolves it

**Comment by JackHack96** [comment]
I also have that option in the BIOS. Better add it to the README!

**Comment by pabb85** [comment]
Thank you @JackHack96 :)
