### ISSUE TITLE
Slow Firefox

### ISSUE THREAD

**Issue by mathewjpotter** [JackHack96/dell-xps-9570-ubuntu-respin#70]
Hi there, recently frustrated at the performance of firefox on this PC running ubuntu vs when running on the same PC with osx mojave (via clover). To make firefox perform faster on this ubuntu respin, disable multiprocess in firefox

go to firefox:

go to the config section by typing "about:config" in the browser and search 

browser.tabs.remote and update the value to false, this will disable multiprocess which will increase your firefox browsing speed to what it should be.

**Comment by JackHack96** [comment]
I think it should be transferred to the wiki, in the troubleshooting page.
BTW I have multi-process Firefox enabled and it works like a charm. I also enabled hardware acceleration and webrender rendering through MOZ_ACCELERATED=1 MOZ_WEBRENDER=1.

If someone wants to enable those flags, it's just simple as editing `.profile` in the home directory and adding this line at the bottom:
`export MOZ_ACCELERATED=1 MOZ_WEBRENDER=1`
