### ISSUE TITLE
Suspend/wake problems when using the NVIDIA card

### ISSUE THREAD

**Issue by anferico** [JackHack96/dell-xps-9570-ubuntu-respin#71]
Hello,

I have installed the already respun ISO and then run the post-installation script. The good thing is that the latest nvidia driver (415) was succesfully installed, and I'm perfectly able to switch between intel and nvidia. Despite this, I have problems after waking from suspend when the nvidia card is selected. In particular, the screen is mostly black and presents a pattern of dots. Of course I can't do anything, and the only solution is to reboot

**Comment by floturcocantsee** [comment]
Sleep mode type is the most common issue with nVidia GPUs in laptops. check your mem_sleep configuration by doing this command: `cat /sys/power/mem_sleep ` if you get [deep] you're configured correctly, if not add this to your kernel command line in grub: `mem_sleep_default=deep`.

**Comment by JackHack96** [comment]
Unfortunately, it's a known problem. Your laptop is configured correctly, but the bug still persists.
I'm sorry I can't help you further than this :cry:

**Comment by erenatas** [comment]
I also have this problem. Funny thing, the problem does not occur on KDE Neon 18.04.

**Comment by anferico** [comment]
> Unfortunately, it's a known problem. Your laptop is configured correctly, but the bug still persists. There are some working cases (like mine), and some not. I still didn't understand the reasons of this issue...
> I'm sorry I can't help you further than this 😢
> Maybe you could try updating the nVidia driver to the latest release (some days ago nVidia released the 418 series), but I don't know if it's going to work.
Would I have to download it and install it directly from the nVidia website? I'm asking this because I've always been told to install nVidia drivers by adding the ppa/graphics-drivers repository to apt. My previous attempts to install graphics drivers directly from nVidia failed. 
Morevoer, the 418 version seems to be still a beta. Anyway, I think I will try. 

> I also have this problem. Funny thing, the problem does not occur on KDE Neon 18.04.
Did you apply the same tweaks suggested in this repository? Or are you saying that everything works on a regular installation of KDE Neon 18.04?

**Comment by erenatas** [comment]
> > Unfortunately, it's a known problem. Your laptop is configured correctly, but the bug still persists. There are some working cases (like mine), and some not. I still didn't understand the reasons of this issue...
> > I'm sorry I can't help you further than this cry
> > Maybe you could try updating the nVidia driver to the latest release (some days ago nVidia released the 418 series), but I don't know if it's going to work.
> 
> Would I have to download it and install it directly from the nVidia website? I'm asking this because I've always been told to install nVidia drivers by adding the ppa/graphics-drivers repository to apt. My previous attempts to install graphics drivers directly from nVidia failed.
> Morevoer, the 418 version seems to be still a beta. Anyway, I think I will try.
> 
> > I also have this problem. Funny thing, the problem does not occur on KDE Neon 18.04.
> 
> Did you apply the same tweaks suggested in this repository? Or are you saying that everything works on a regular installation of KDE Neon 18.04?

After installing KDE Neon 18.04, I have executed @JackHack96 's script and let it install everything. You could also try out and see if you reproduce this problem.

**Comment by anferico** [comment]
KDE Neon 18.04 seems to work just fine! Actually, when I try to wake from suspend in nVidia mode, it sometimes still happens that the screen displays that weird dots pattern, but this time moving the cursor using the touchpad removes the pattern!

**Comment by erenatas** [comment]
@anferico it's really weird right?
