### ISSUE TITLE
Respin Xubuntu ISO?

### ISSUE THREAD

**Issue by philiporlando** [JackHack96/dell-xps-9570-ubuntu-respin#73]
Before I try this out on my new install I wanted to clarify if the manual respin will work for other flavors of Ubuntu, e.g. Xubuntu, Lubuntu, Kubuntu, MATE?

Thanks for providing these amazing tools.

**Comment by ToonvanStrijp** [comment]
The respin worked for me on Ubuntu Budgie 18.10 with some small changes

**Comment by JackHack96** [comment]
I only tested it on Ubuntu 18.04, but some users like @ToonvanStrijp reported that it works on other flavors too (though I can't offer support for that)

**Comment by philiporlando** [comment]
I'm having success with Xubuntu 18.04 LTS. I applied the post install script and things appear to be working great so far!

Really awesome work @JackHack96. Big thank you for putting this out there!
