### ISSUE TITLE
[NOT REALLY AN ISSUE] HDMI on Intel GPU

### ISSUE THREAD

**Issue by Sangeppato** [JackHack96/dell-xps-9570-ubuntu-respin#75]
Hey, thanks for your great work!
I have one question: Does the HDMI/DP port work with the discrete GPU turned off (so running on Intel-only)?

I'm interested in the 9570 to run Linux, but a guy told me that you can't use the HDMI port with the Nvidia card turned off, because it is wired directly to it (since it's 2.0).
Is this true?

Thanks and sorry if this is not the most appropriate location to ask, but I really don't know where to get this information..

**Comment by ToonvanStrijp** [comment]
HDMI still works fine when the Nvidia is disabled (I've mine completely turned off) and when I connect HDMI it works perfectly ;)

I'm running Ubuntu 18.10 (Budgie)

**Comment by Sangeppato** [comment]
Thanks, that's a very good news!
Have you disabled it with bbsiwtch or something like that?

**Comment by ToonvanStrijp** [comment]
I did it by creating a service that runs on boot:

# gpuoff.service
```
[Unit]
Description=Power-off gpu

[Service]
Type=oneshot
ExecStart=/bin/bash -c "if [[ `prime-select query` == 'intel' ]]; then echo auto > /sys/bus/pci/devices/0000\:01\:00.0/power/control; fi"

[Install]
WantedBy=default.target
```

put this file in this folder: `/lib/systemd/system/`

Then run: `sudo systemctl enable gpuoff`

only thing now is do a reboot and you're nvidia should be disabled/turned off. If you wish to use it run `prime-select nvidia` and reboot your laptop.

**Comment by JackHack96** [comment]
I can confirm that HDMI with Intel GPU works, because I never use the nVidia card but I sometime use an external monitor plugged with HDMI :)

**Comment by Sangeppato** [comment]
@ToonvanStrijp 
Cool, I've writter a similar script to manage the dGPU on my laptop as well!

Thanks guys, this is great to hear!

@JackHack96 ho realizzato ora che sei Italiano.. Grazie per il lavoro da un connazionale :)

**Comment by JackHack96** [comment]
@Sangeppato Hahaha avevo immaginato dal nome "Sangeppato" :laughing:

**Comment by nithjino** [comment]
I don't want to create a new issue for this so I'm commenting here. Does sound work through HDMI if using the Intel GPU?

**Comment by szkocot** [comment]
@nithjino Yes. Tested with my AOC WQHD  monitor.

**Comment by JackHack96** [comment]
@nithjino I confirm it's working (tested with a projector at University)
