### ISSUE TITLE
mouse / keyboard / touchscreen not working after running script

### ISSUE THREAD

**Issue by lepirlouit** [JackHack96/dell-xps-9570-ubuntu-respin#80]
Hi,
after running the script, mouse, keyboard and touchscreen is not responding anymore.

when I run cat /dev/input/mouse* I seee that these device are all responding well.
numlock is not wroking

this is on a fresh installation of ubuntu 18.04

**Comment by lepirlouit** [comment]
I can still login via ssh

**Comment by lepirlouit** [comment]
seems to be related with powermanagement, 
I runned powertop , and put all devices in "bad" state
I'm sure this is not the perfect choice
after reboot, all input devices are working again

**Comment by JackHack96** [comment]
This is the first time someone reports me this behaviour.
The "bad" state powertop reports aren't involved, it simply states that the "bad" devices are consuming more energy than necessary.
Try uninstalling TLP and see if it change something.
