### ISSUE TITLE
Nvidia gtx 1050 ti driver fix

### ISSUE THREAD

**Issue by AnisimovAM** [JackHack96/dell-xps-9570-ubuntu-respin#81]
Hello,
My laptop is good working with gtx 1050 ti.

I have installed latest driver nvidia-418 https://www.nvidia.com/Download/driverResults.aspx/142958/en-us

sudo apt install ubuntu-drivers-common
ubuntu-drivers devices
ubuntu-drivers autoinstall

I haven`t problems with sleep/wake on nvidia

**Comment by grybouilli** [comment]
Hey,
are your fans quiet?

**Comment by AnisimovAM** [comment]
Yes, sometimes fans is working
There are setting in **NVIDIA X Server Settings** app.
Set adaprive perfomance profile.

**Comment by grybouilli** [comment]
That's great, I'll try it out then!

**Comment by AnisimovAM** [comment]
![screenshot-1](https://user-images.githubusercontent.com/3782720/54257833-38fb1980-4593-11e9-830b-3114ab71cd4e.png)
