### ISSUE TITLE
Trouble installing Ubuntu

### ISSUE THREAD

**Issue by a3020** [JackHack96/dell-xps-9570-ubuntu-respin#85]
Hi, thanks for maintaining this repository!

I have trouble installing Ubuntu. The issue is that during the "Install system" step (the one after copying the files), the process just hangs.The cursor also stops moving. The fans are on, so I guess something is done, but I'm not sure what.

Steps I performed on an XPS 15 9570 i9:
- Flash ISO with balenaEtcher on a pen drive.
- Try to install Ubuntu on an HDD where Win10 is also active, but on a separate formatted EXT4 partition.
- Do not connect with WiFi (although this doesn't seem to make a difference).
- Do not install 3rd party drivers.

Am I missing something?

Thanks in advance for your reply!

**Comment by JackHack96** [comment]
Have you checked on the BIOS that the AHCI option is enabled (and not RAID)?
Also, check if secure boot is disabled, it only causes troubles

**Comment by a3020** [comment]
Yes, AHCI is enabled and secure boot is disabled.

I just flashed a pendrive with a patched ISO via your build tool, but I'm experiencing the same problems. Basically the laptop just hangs during set up / configuration or during the installation of Ubuntu.

**Comment by JackHack96** [comment]
Does the official ISO have the same problem?

**Comment by a3020** [comment]
I used the ISO from ubuntu.com (18.04.2) and then ran the `build.sh` script. That ISO gives the same problems. 

The boot menu gives the following options:

**LEGACY EXTERNAL DEVICE BOOT:**
USB Storage Device

**UEFI BOOT:**
Windows Boot Manager
USB
UEFI: 8.07
UEFI: 8.07 Partition 2

**OTHER OPTIONS:**
BIOS setup
BIOS Flash Update
Diagnostics
Change Boot Mode Settings

I used 'USB Storage Device'.

**Comment by a3020** [comment]
OK, I think I found the problem. In my BIOS the option 'Enable Legacy Option ROMs' was enabled. That's why that first option was shown. However, I should use the **UEFI: 8.07** option instead. It's currently running the installation and so far it looks good 👍 

@JackHack96 thanks for your help on the way ;)
