### ISSUE TITLE
Stupid question: differences between the iso and the post-install script

### ISSUE THREAD

**Issue by ragloo** [JackHack96/dell-xps-9570-ubuntu-respin#88]
So may I ask this stupid question ? 
Are there differences between this iso and a fresh installed ubuntu 18.04 where we applied the post-install script ?
Thanks for your awesome work :+1:

**Comment by JackHack96** [comment]
No differences. The ISO was made because it wasn't possible to boot Ubuntu without touching the kernel parameters, but nowadays I suggest installing Ubuntu directly and then applying the script.

**Comment by ragloo** [comment]
Many thanks @JackHack96 for this precision.
I really enjoy your work, congrats for this awesome job
