### ISSUE TITLE
Booting Errors

### ISSUE THREAD

**Issue by tur-nr** [JackHack96/dell-xps-9570-ubuntu-respin#9]
Firstly, thanks for your re-spin. I have been waiting since I got my new laptop to put Ubuntu on it so kudos.

Everything seems to be working fine after boot, however I get some errors during. It hangs for 20+ secs and then Ubuntu login screen is displayed. Any suggestions on how to fix this or get the boot time to be more responsive?

![mvimg_20180730_131932](https://user-images.githubusercontent.com/817134/43382371-ea917c96-941a-11e8-9938-656cc5e4afd2.jpg)

**Comment by JackHack96** [comment]
I get those errors too, but I don't think they are the cause of your "slow" boot (my laptop boots in more or less 10 seconds).

It could be a systemd unit, try to see with `systemd-analyze blame` who is slowing down the boot process.
