### ISSUE TITLE
[Question] ath10k firmware-6.bin

### ISSUE THREAD

**Issue by nicolo-ribaudo** [JackHack96/dell-xps-9570-ubuntu-respin#93]
I currently have 4 .bin files in the `/lib/firmware/ath10k/QCA6174/hw3.0` folder:

```
# ls /lib/firmware/ath10k/QCA6174/hw3.0
board-2.bin  firmware-4.bin  notice_ath10k_firmware-4.txt
board.bin    firmware-6.bin  notice_ath10k_firmware-6.txt
```

I noticed that this script doesn't install `firmware-6`: is it expected?
https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/blob/6cf3bd02b6c9c33ff788d4f8f3fa889c41c1ae2d/xps-tweaks.sh#L152-L156

**Comment by JackHack96** [comment]
Yes, it's expected. This is from the original XPS 9560 project :smile:
