### ISSUE TITLE
Stuttering/low fps (?) scrolling

### ISSUE THREAD

**Issue by Sleort** [JackHack96/dell-xps-9570-ubuntu-respin#94]
I just installed (dual boot) Ubuntu 19.04 on my brand new Xps 9570 (16GB ram, i7-8750H, GTX 1050 Ti) and ran your nice script. Everything seems to work flawlessly (thank you!), *except* that scrolling in e.g. a browser (I tested both Firefox and Chromium) or a pdf (Evince) is stuttering/lagging quite a lot, as if the frame rate has been lowered. (Other people seems to have [similar experiences](https://www.reddit.com/r/Ubuntu/comments/afzy99/scrolling_stutterlag_on_ubuntu_1804_1810/) with earlier Ubuntu versions) This is the case both when I'm using the integrated Intel GPU and the discrete Nvidia GPU. (It's significantly worse than what I experience in Windows or on my 6 year old laptop running Ubuntu 16.04.) Is this something known/you've experienced too? And is there a way to fix it?

I tried to follow [the graphic stuttering advice](https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/wiki/Troubleshooting#graphic-stuttering) in the Troubleshooting wiki, but I didn't notice any improvements when doing so...

**Comment by JackHack96** [comment]
Uhm, honestly I'm not seeing any lag while scrolling (even on the video posted on reddit) sorry :disappointed: 

Do you perceive the same problem with all extensions disabled (https://askubuntu.com/questions/1061727/18-04-gnome-stutters-every-second-after-running-for-a-while)?

I know there was some work from Ubuntu devs for missing frame and stutter on GNOME (https://www.reddit.com/r/gnome/comments/7tcnhw/is_gnome_laggy_for_anyone_else/, https://trello.com/c/Q6JYXPPs/22-gnome-shell-performance-stuttering-and-missed-frames)

**Comment by Sleort** [comment]
It may be a bit subtle (especially if you've gotten used to it). It's like the frame rate has gone significantly down, making reading while scrolling uncomfortable (compared to my Windows or Ubuntu 16.04 experience). (You may need to view the Reddit video in full-screen to notice the effect.)

Turning off the few extensions I had activated didn't change anything. But yeah, this could be a more general GNOME issue; I've noticed that also the changing-workspace animation isn't as smooth as it used to be...

Anyway, thanks for the feedback! I'll see if I can find some solution. If not, I guess I have to give some other desktop environment a try.

**Comment by DonkeyShot21** [comment]
Have you tried this: https://wiki.ubuntu.com/Kernel/LTSEnablementStack
Still not super smooth as Windows but it helped.
