### ISSUE TITLE
Fans are always spinning | SOLVED

### ISSUE THREAD

**Issue by leofabri** [JackHack96/dell-xps-9570-ubuntu-respin#95]
Hi, I installed your script on Ubuntu 19 but I noticed that the two fans are never turning off. Even when the laptop is cool. 
I think that the problem is not caused by your script, it was present even when I first installed ubuntu. Are your fans turning off sometimes?

**Comment by leofabri** [comment]
I am also trying to reinstall Ubuntu using the isorespin tool, but when I execute the command 

> sudo ./build.sh -i ubuntu-19.04-desktop-amd64

I get the following error:

> Video codecs will be installed
> SPECTRE/Meltdown patches will be used
> Extracting ISO ...
> ./isorespin.sh: Cannot determine EOL for ISO.

**Comment by szkocot** [comment]
Try setting dell power profile to quiet and disconnect from AC. If it is okay, then you can manually set battery mode in tlp and disable auto switching to AC mode when connected to power supply.

**Comment by leofabri** [comment]
I don't know what happened but after closing the lid of the laptop, and opening it again after some time the fan didn't turn on so I suppose that it's working fine. Thank you all
