### ISSUE TITLE
Screen freezes when using NVIDIA GPU under Ubuntu 19.04

### ISSUE THREAD

**Issue by yourithielen** [JackHack96/dell-xps-9570-ubuntu-respin#96]
Hi,

First of all, lots of kudos for maintaining this repo.

The only issue I'm having is that when I select the NVDIA GPU I'm having complete screen freezes every now and then. When I switch back to Intel (Power Saving Mode) everything works fine.

Is there something else I need to besides running `xps-tweaks.sh`? 

Have tried gaming in Windows using the NVIDIA card and that works fine. Also, tried different driver version in the `aditional drivers` section in `Software & Updates`.

Cheers!

**Comment by JackHack96** [comment]
I have to say I use the nVidia GPU very rarely (for CUDA or for gaming with Citra 3DS emulator), but I never experienced this issue. I'm using the latest 418 driver and the official 5.0 kernel that comes with 19.04

**Comment by yourithielen** [comment]
Will try to figure out when this occurs but fo now it seems to be pretty random. It might have something to do with my external monitor. Will update this issue if I know more.

**Comment by blake5634** [comment]
I'm having this issue with a very new XPS-15 9570 and a fresh kubuntu 18.04 install.    I'm going to try this script and see what happens.

**Comment by yourithielen** [comment]
I'm using the Intel GPU and haven't had the issue anymore, also don't need the Nvidia GPU under Ubuntu so for me the problem is solved.

**Comment by vikrambombhi** [comment]
@yourithielen next time it freezes run `nvidia-bug-report.sh` it will create a log file for debugging

**Comment by blake5634** [comment]
A few hours in it's more stable.  Display seems great in both Intel and Nvidia modes.   I've had one touchpad freeze in which cursor can move but I can't click anything.

**Comment by blake5634** [comment]
The not-able-to-click issue seems to occur after sleep/wake.  I can fix it by switching to a console and back to the KDE environment.     HOWEVER, in this laptop you have to do CTL-ALT-FN-F3 instead of CTL-ALT-F3 as in my previous several laptop installs.

**Comment by JackHack96** [comment]
Ok now that I'm heavily using the nVidia card for the CUDA course at University, I frequently experience this issue, though I don't know why it happens...

**Comment by thedarb** [comment]
I had these same issues with ubuntu 19.10 beta and the 418 driver.  Things that fixed this for me was an upgrade to the 430 driver, and 'sudo apt purge xserver-xorg-video-nouveau', and 'sudo apt autoremove', and 'sudo update-initramfs -u'.  I'm running Cinnamon desktop on X11.  Then I found on google a few places (like here) that also recommended 'nouveau.blacklist=1 acpi_rev_override=1 acpi_osi=Linux nouveau.modeset=0 pcie_aspm=force drm.vblankoffdelay=1 scsi_mod.use_blk_mq=1 nouveau.runpm=0 mem_sleep_default=deep' for my grub command line, which these fixed my laptop  being able to suspend properly.  Hopefully some or all of this might help you with your 19.04 installation.

**Comment by robsigler** [comment]
I experience the same on Ubuntu 19.04 and Gnome with the nvidia-418 driver. Could this be the issue? https://gitlab.gnome.org/GNOME/gnome-shell/issues/1202

I worked around it by using XFCE when I'm using the nvidia card..

**Comment by JackHack96** [comment]
> I experience the same on Ubuntu 19.04 and Gnome with the nvidia-418 driver. Could this be the issue? [gitlab.gnome.org/GNOME/gnome-shell/issues/1202](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1202)
> 
> I worked around it by using XFCE when I'm using the nvidia card..

Yes, it's that one!
By the way, you can workaround this annoying bug by appending `export __GL_MaxFramesAllowed=1` in `~/.profile`
