### ISSUE TITLE
Trying to respin from WSL throws an error: `./isorespin.sh: Access to the internet is required for downloading files.`

### ISSUE THREAD

**Issue by serpro69** [JackHack96/dell-xps-9570-ubuntu-respin#97]
Not sure if it's supported but would be nice to be able to respin the iso from WSL under windows.

Right now getting an error from `isorespin.sh: Access to the internet is required for downloading files.`

**Comment by JackHack96** [comment]
Well, I never ever tested it on the WSL. From the error string I suppose the problem is not in my script, but with isorespin.sh, which isn't mine.

**Comment by serpro69** [comment]
I have tried running the build from Linux Mint and still getting the same error: `isorespin.sh: Access to the internet is required for downloading files.`
Commented out the `CLEAN_EXIT` inside the function that checks internet connection and build seemed to work fine (at least finished without any errors).
