### ISSUE TITLE
Documentation: Is there any difference between running post-install script and respining the iso?

### ISSUE THREAD

**Issue by serpro69** [JackHack96/dell-xps-9570-ubuntu-respin#98]
Could you please update the readme with the differences between running post-install script and respining the iso? 

I'm having some troubles with respin (for some reason the iso does not have video drivers and some other packages, however running the post install script seems to work just fine). 

Wondering if it's worth the trouble to try to respin again or the end result from respin and post-install script is the same?

And many thanks for an amazing repo!

**Comment by JackHack96** [comment]
The difference is that the respin provides you all the tweaks at install time.
That was useful when the stock 18.04 ISO could not boot by default on the 9570.

Therefore I suggest you to use the post install tweaks
